/**
 * Prettier config file.
 *
 * @since 1.0.0
 *
 * @note Prettier is not aware of this config file's location.
 *       Please extend this file using `../../../.prettierrc.cjs`.
 *
 * @see https://prettier.io/docs/en/configuration.html
 *
 * @note PLEASE DO NOT EDIT THIS FILE!
 * This file and the contents of it are updated automatically.
 * - Instead of editing this file, please review source repository {@see https://o5p.me/LevQOD}.
 */
/* eslint-env es2021, node */

module.exports = {
	arrowParens                : 'always',
	bracketSameLine            : false,
	bracketSpacing             : true,
	embeddedLanguageFormatting : 'auto',
	endOfLine                  : 'lf',
	htmlWhitespaceSensitivity  : 'css',
	insertPragma               : false,
	jsxSingleQuote             : true,
	printWidth                 : 99999999,
	proseWrap                  : 'preserve',
	quoteProps                 : 'as-needed',
	requirePragma              : false,
	semi                       : true,
	singleQuote                : true,
	tabWidth                   : 4,
	trailingComma              : 'es5',
	useTabs                    : true,
	vueIndentScriptAndStyle    : true,
	xmlSelfClosingSpace        : true,
	xmlWhitespaceSensitivity   : 'strict',
};
