##
# NPM config file.
#
# @since 1.0.0
#
# @note NPM is aware of this config file's location.
#
# @note PLEASE DO NOT EDIT THIS FILE!
# This file and the contents of it are updated automatically.
# - Instead of editing this file, please see source repository @ <https://git.io/JD8Zo>.
##

access=public
engine-strict=true
//registry.npmjs.org/:_authToken=${C10N_NPM_TOKEN}
//npm.pkg.github.com/:_authToken=${C10N_GITHUB_TOKEN}
