#!/usr/bin/env bash
# shellcheck disable=SC2129,SC2016
##
# WP docker entrypoint.
#
# @since 1.0.0
#
# @note PLEASE DO NOT EDIT THIS FILE!
# This file and the contents of it are updated automatically.
# Instead of editing this file, please edit `./.wp-docker.prj.sh`.
##
# ---------------------------------------------------------------------------------------------------------------------
# macOS Docker installation for compatibility with this configuration.
# ---------------------------------------------------------------------------------------------------------------------
# $ brew install --cask docker;
# $ brew install chipmk/tap/docker-mac-net-connect;
# $ sudo brew services start chipmk/tap/docker-mac-net-connect; # {@see https://o5p.me/Q9hnml}.
# ---------------------------------------------------------------------------------------------------------------------

WORDPRESS_DIR=/var/www/html; # Apache `DOCUMENT_ROOT` directory.
WWW_DATA_HOME_DIR=/var/www;  # `www-data` user's home directory.

if [[ "${X_COMPOSE_VARIANT:-}" == 'ci' ]]; then
	WORDPRESS_URL=http://localhost; # See `./.wp-docker-ci.yml`.
else
	WORDPRESS_URL=http://"${X_COMPOSE_PROJECT_SLUG}".dkr; # Requires DNS.
	# DNS mapping is beyond the scope of this file. That's handled elsewhere.
fi;
# Run parent container's entrypoint before we continue.
# The `apache2-noop` name is important. Noting because it's extremely non-obvious.
# Take a peek at the top of `docker-entrypoint.sh` to see why `apache2` is key; {@see https://o5p.me/j70ja4}.

if [[ ! -f /usr/local/bin/apache2-noop ]]; then
	echo "#!/usr/bin/env bash" > /usr/local/bin/apache2-noop;
	chmod +x /usr/local/bin/apache2-noop;
fi;
/usr/local/bin/docker-entrypoint.sh apache2-noop;

# Maybe install WP-CLI phar file.

if [[ ! -f /usr/local/bin/wp ]]; then
	apt-get update; apt-get install curl;
	curl -L https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar -o /usr/local/bin/wp;
	chmod +x /usr/local/bin/wp; # Make it executable.
fi;
# Maybe install a WP-CLI config file.

if [[ ! -f "${WWW_DATA_HOME_DIR}"/.wp-cli/config.yml ]]; then
	mkdir                                         "${WWW_DATA_HOME_DIR}"/.wp-cli;
	echo "path: ${WORDPRESS_DIR}"               > "${WWW_DATA_HOME_DIR}"/.wp-cli/config.yml;
	echo "url: ${WORDPRESS_URL}"               >> "${WWW_DATA_HOME_DIR}"/.wp-cli/config.yml;
	echo "user: ${X_WORDPRESS_ADMIN_USERNAME}" >> "${WWW_DATA_HOME_DIR}"/.wp-cli/config.yml;
fi;
# Maybe install WordPress core, plugins, and themes.

if ! wp core is-installed --allow-root --path="${WORDPRESS_DIR}" --url="${WORDPRESS_URL}"; then
	# Install WordPress core.

	wp core install --allow-root --path="${WORDPRESS_DIR}" --url="${WORDPRESS_URL}" \
		--title="${X_WORDPRESS_SITE_TITLE}" \
		--admin_user="${X_WORDPRESS_ADMIN_USERNAME}" \
		--admin_password="${X_WORDPRESS_ADMIN_PASSWORD}" \
		--admin_email="${X_WORDPRESS_ADMIN_EMAIL}" --skip-email;

	# Maybe update `.htaccess` file for mulitisite installs.

	if [[ "${X_WORDPRESS_MULTISITE_TYPE}" == 'subdomains' ]]; then
		wp core multisite-convert --allow-root --path="${WORDPRESS_DIR}" --url="${WORDPRESS_URL}" \
			--title="${X_WORDPRESS_SITE_TITLE}" --subdomains;

		echo 'RewriteEngine On'                                                          > "${WORDPRESS_DIR}"/.htaccess;
		echo 'RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]'            >> "${WORDPRESS_DIR}"/.htaccess;
		echo 'RewriteBase /'                                                            >> "${WORDPRESS_DIR}"/.htaccess;
		echo 'RewriteRule ^index\.php$ - [L]'                                           >> "${WORDPRESS_DIR}"/.htaccess;
		echo ''                                                                         >> "${WORDPRESS_DIR}"/.htaccess;
		echo 'RewriteRule ^wp-admin$ wp-admin/ [R=301,L]'                               >> "${WORDPRESS_DIR}"/.htaccess;
		echo ''                                                                         >> "${WORDPRESS_DIR}"/.htaccess;
		echo 'RewriteCond %{REQUEST_FILENAME} -f [OR]'                                  >> "${WORDPRESS_DIR}"/.htaccess;
		echo 'RewriteCond %{REQUEST_FILENAME} -d'                                       >> "${WORDPRESS_DIR}"/.htaccess;
		echo 'RewriteRule ^ - [L]'                                                      >> "${WORDPRESS_DIR}"/.htaccess;
		echo 'RewriteRule ^(wp-(content|admin|includes).*) $1 [L]'                      >> "${WORDPRESS_DIR}"/.htaccess;
		echo 'RewriteRule ^(.*\.php)$ $1 [L]'                                           >> "${WORDPRESS_DIR}"/.htaccess;
		echo 'RewriteRule . index.php [L]'                                              >> "${WORDPRESS_DIR}"/.htaccess;

	elif [[ -n "${X_WORDPRESS_MULTISITE_TYPE}" ]]; then
		wp core multisite-convert --allow-root --path="${WORDPRESS_DIR}" --url="${WORDPRESS_URL}" \
			--title="${X_WORDPRESS_SITE_TITLE}";

		echo 'RewriteEngine On'                                                          > "${WORDPRESS_DIR}"/.htaccess;
		echo 'RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]'            >> "${WORDPRESS_DIR}"/.htaccess;
		echo 'RewriteBase /'                                                            >> "${WORDPRESS_DIR}"/.htaccess;
		echo 'RewriteRule ^index\.php$ - [L]'                                           >> "${WORDPRESS_DIR}"/.htaccess;
		echo ''                                                                         >> "${WORDPRESS_DIR}"/.htaccess;
		echo 'RewriteRule ^([_0-9a-zA-Z-]+/)?wp-admin$ $1wp-admin/ [R=301,L]'           >> "${WORDPRESS_DIR}"/.htaccess;
		echo ''                                                                         >> "${WORDPRESS_DIR}"/.htaccess;
		echo 'RewriteCond %{REQUEST_FILENAME} -f [OR]'                                  >> "${WORDPRESS_DIR}"/.htaccess;
		echo 'RewriteCond %{REQUEST_FILENAME} -d'                                       >> "${WORDPRESS_DIR}"/.htaccess;
		echo 'RewriteRule ^ - [L]'                                                      >> "${WORDPRESS_DIR}"/.htaccess;
		echo 'RewriteRule ^([_0-9a-zA-Z-]+/)?(wp-(content|admin|includes).*) $2 [L]'    >> "${WORDPRESS_DIR}"/.htaccess;
		echo 'RewriteRule ^([_0-9a-zA-Z-]+/)?(.*\.php)$ $2 [L]'                         >> "${WORDPRESS_DIR}"/.htaccess;
		echo 'RewriteRule . index.php [L]'                                              >> "${WORDPRESS_DIR}"/.htaccess;
	fi;
	# Maybe install plugins|themes network-wide.

	if [[ -n "${X_WORDPRESS_MULTISITE_TYPE}" ]]; then
		if [[ -n "${X_WORDPRESS_INSTALL_PLUGINS}" ]]; then
			while IFS=',' read -ra _x_wordpress_install_plugins; do
				for _x_wordpress_install_plugin in "${_x_wordpress_install_plugins[@]}"; do
				wp plugin install --allow-root --path="${WORDPRESS_DIR}" --url="${WORDPRESS_URL}" \
					"${_x_wordpress_install_plugin}" --activate-network;
				done;
			done <<< "${X_WORDPRESS_INSTALL_PLUGINS}";
		fi;
		if [[ -n "${X_WORDPRESS_INSTALL_THEME}" && -n "${X_WORDPRESS_INSTALLED_THEME_SLUG}" ]]; then
			wp theme install --allow-root --path="${WORDPRESS_DIR}" --url="${WORDPRESS_URL}" \
				"${X_WORDPRESS_INSTALL_THEME}";

			wp theme enable --allow-root --path="${WORDPRESS_DIR}" --url="${WORDPRESS_URL}" \
				"${X_WORDPRESS_INSTALLED_THEME_SLUG}" --network --activate;
		fi;
	# Maybe install plugins|themes for standard WordPress.
	else
		if [[ -n "${X_WORDPRESS_INSTALL_PLUGINS}" ]]; then
			while IFS=',' read -ra _x_wordpress_install_plugins; do
				for _x_wordpress_install_plugin in "${_x_wordpress_install_plugins[@]}"; do
				wp plugin install --allow-root --path="${WORDPRESS_DIR}" --url="${WORDPRESS_URL}" \
					"${_x_wordpress_install_plugin}" --activate;
				done;
			done <<< "${X_WORDPRESS_INSTALL_PLUGINS}";
		fi;
		if [[ -n "${X_WORDPRESS_INSTALL_THEME}" ]]; then
			wp theme install --allow-root --path="${WORDPRESS_DIR}" --url="${WORDPRESS_URL}" \
				"${X_WORDPRESS_INSTALL_THEME}" --activate;
		fi;
	fi;
	# Maybe link a project's WordPress plugin|theme directory and activate.

	if [[ "${X_COMPOSE_PROJECT_TYPE}" == 'library' && "${X_COMPOSE_PROJECT_LAYOUT}" == 'wp-plugin' && -f /x-host/project/trunk/plugin.php ]]; then
		ln -s /x-host/project/trunk "${WORDPRESS_DIR}"/wp-content/plugins/"${X_COMPOSE_PROJECT_SLUG}";

		if [[ -n "${X_WORDPRESS_MULTISITE_TYPE}" ]]; then
			wp plugin activate --allow-root --path="${WORDPRESS_DIR}" --url="${WORDPRESS_URL}" \
				"${X_COMPOSE_PROJECT_SLUG}" --network;
		else
			wp plugin activate --allow-root --path="${WORDPRESS_DIR}" --url="${WORDPRESS_URL}" \
				"${X_COMPOSE_PROJECT_SLUG}";
		fi;
	elif [[ "${X_COMPOSE_PROJECT_TYPE}" == 'library' && "${X_COMPOSE_PROJECT_LAYOUT}" == 'wp-theme' && -f /x-host/project/trunk/theme.php ]]; then
		ln -s /x-host/project/trunk "${WORDPRESS_DIR}"/wp-content/themes/"${X_COMPOSE_PROJECT_SLUG}";

		if [[ -n "${X_WORDPRESS_MULTISITE_TYPE}" ]]; then
			wp theme enable --allow-root --path="${WORDPRESS_DIR}" --url="${WORDPRESS_URL}" \
				"${X_COMPOSE_PROJECT_SLUG}" --network --activate;
		else
			wp theme enable --allow-root --path="${WORDPRESS_DIR}" --url="${WORDPRESS_URL}" \
				"${X_COMPOSE_PROJECT_SLUG}" --activate;
		fi;
	fi;
fi;
# Run the project-specific entrypoint hook.

/x-host/project/.wp-docker.prj.sh;

# Start Apache.

apache2-foreground;
