#!/usr/bin/env bash
# shellcheck disable=SC2129,SC2016
##
# WP docker image setup.
#
# @since 1.0.0
#
# @note PLEASE DO NOT EDIT THIS FILE!
# This file and the contents of it are updated automatically.
# Instead of editing this file, please edit `./dev/.libs/docker/wp/compose~prj.yml`.
##
# ---------------------------------------------------------------------------------------------------------------------
# Source a few dependencies.
# ---------------------------------------------------------------------------------------------------------------------

. /wp-docker/host/project/dev/utilities/load.bash;
. /wp-docker/host/project/dev/utilities/bash/partials/require-root;

# ---------------------------------------------------------------------------------------------------------------------
# Define a few variables.
# ---------------------------------------------------------------------------------------------------------------------

ROOT_HOME_DIR=/root;         # `root` user's home directory.
WWW_DATA_HOME_DIR=/var/www;  # `www-data` user's home directory.
WORDPRESS_DIR=/var/www/html; # Apache `DOCUMENT_ROOT` directory.

# ---------------------------------------------------------------------------------------------------------------------
# Run parent container's entrypoint before we continue.
# The `apache2-noop` name is important. Noting because it's extremely non-obvious.
# Take a peek at the top of `docker-entrypoint.sh` to see why `apache2` is key; {@see https://o5p.me/j70ja4}.
# ---------------------------------------------------------------------------------------------------------------------

if [[ ! -f /usr/bin/apache2-noop ]]; then
	echo '#!/usr/bin/env bash' > /usr/bin/apache2-noop;
	chmod +x /usr/bin/apache2-noop;
fi;
/usr/local/bin/docker-entrypoint.sh apache2-noop;

# ---------------------------------------------------------------------------------------------------------------------
# Maybe run setup routines.
# ---------------------------------------------------------------------------------------------------------------------

if [[ ! -f /wp-docker/image/setup-complete ]]; then
	mkdir --parents /wp-docker/image;
	touch /wp-docker/image/setup-complete;

	# -----------------------------------------------------------------------------------------------------------------
	# Aptitude.
	# -----------------------------------------------------------------------------------------------------------------

	apt-get update --yes;

	# -----------------------------------------------------------------------------------------------------------------
	# Core utilities.
	# -----------------------------------------------------------------------------------------------------------------

	apt-get install man --yes;
	apt-get install coreutils --yes;

	# -----------------------------------------------------------------------------------------------------------------
	# Build tools.
	# -----------------------------------------------------------------------------------------------------------------

	apt-get install build-essential --yes;
	apt-get install g++ --yes;
	apt-get install cmake --yes;
	apt-get install expect --yes;
	apt-get install libtool --yes;
	apt-get install autoconf --yes;
	apt-get install pkg-config --yes;

	# -----------------------------------------------------------------------------------------------------------------
	# Other tools; grouped broadly by function.
	# -----------------------------------------------------------------------------------------------------------------

	apt-get install tar zip gzip unzip --yes;
	apt-get install curl wget rsync --yes;
	apt-get install telnet netcat --yes;
	apt-get install openssl gpg --yes;
	apt-get install tmux screen --yes;
	apt-get install tree ack grok less --yes;
	apt-get install gettext pandoc --yes;
	apt-get install vim nano --yes;
	apt-get install ncdu htop --yes;
	apt-get install sudo acl pwgen --yes;
	apt-get install apache2-utils --yes;
	apt-get install git subversion --yes;
	apt-get install perl ruby python3 --yes;
	apt-get install nodejs npm --yes;

	# -----------------------------------------------------------------------------------------------------------------
	# Give `www-data` a default login shell; and write access to its own HOME directory.
	# -----------------------------------------------------------------------------------------------------------------

	chsh  --shell /bin/bash www-data;
	chmod --recursive 0700     "${WWW_DATA_HOME_DIR}";
	chown --recursive www-data "${WWW_DATA_HOME_DIR}";

	# -----------------------------------------------------------------------------------------------------------------
	# Simple shell enhancements.
	# -----------------------------------------------------------------------------------------------------------------

	apt-get install bash-completion --yes;

	rm    --force                                         "${ROOT_HOME_DIR}"/.bashrc;
	touch                                                 "${ROOT_HOME_DIR}"/.profile;
	chmod 0600                                            "${ROOT_HOME_DIR}"/.profile;

	{   echo 'export PS1="🐳 \[\e[32m\]\h\[\e[m\] \[\e[34m\][\[\e[m\]\[\e[33m\]\w\[\e[m\]\[\e[34m\]]\[\e[m\] \\$ ";';

		echo 'alias ls='"'"'ls -la --color=auto'"'"';';
		echo 'function cd() { builtin cd "${@}" && ls; };';
		echo 'function up() { cd ../ || return 1; };';
		echo 'function back() { cd - || return 1; };';
		echo 'function home() { cd ~/ || return 1; };';

		echo 'if [ -f /etc/bash_completion ]; then';
		echo '	. /etc/bash_completion;';
		echo 'fi;';
	} >> "${ROOT_HOME_DIR}"/.profile;

	cp    --preserve=all "${ROOT_HOME_DIR}"/.profile "${WWW_DATA_HOME_DIR}"/.profile;
	chown www-data                                   "${WWW_DATA_HOME_DIR}"/.profile;

	# -----------------------------------------------------------------------------------------------------------------
	# Install Composer.
	# -----------------------------------------------------------------------------------------------------------------

	curl --location https://getcomposer.org/installer \
		 | php -- --install-dir=/usr/local/bin --filename=composer;

	# -----------------------------------------------------------------------------------------------------------------
	# Install PHPUnit.
	# -----------------------------------------------------------------------------------------------------------------

	curl --location https://phar.phpunit.de/phpunit.phar \
		 --output /usr/local/bin/phpunit;
	chmod +x /usr/local/bin/phpunit;

	# -----------------------------------------------------------------------------------------------------------------
	# Install Psysh.
	# -----------------------------------------------------------------------------------------------------------------

	curl --location https://psysh.org/psysh \
		 --output /usr/local/bin/psysh;
	chmod +x /usr/local/bin/psysh;

	if [[ ! -d "${ROOT_HOME_DIR}"/.config ]]; then
		mkdir      "${ROOT_HOME_DIR}"/.config;
		chmod 0700 "${ROOT_HOME_DIR}"/.config;
	fi;
	if [[ ! -d "${ROOT_HOME_DIR}"/.config/psysh ]]; then
		mkdir      "${ROOT_HOME_DIR}"/.config/psysh;
		chmod 0700 "${ROOT_HOME_DIR}"/.config/psysh;
	fi;
	{   echo '<?php';
		echo 'use Clever_Canyon\\{Utilities as U};';
		echo "if ( is_file( '/wp-docker/host/project/vendor/autoload.php' ) ) {";
		echo "    require_once '/wp-docker/host/project/vendor/autoload.php';";
		echo "    U\\Env::set_debug_mode( 'psysh' );";
		echo '}';
		echo 'return [];';
	} > "${ROOT_HOME_DIR}"/.config/psysh/config.php;
	chmod 0600 "${ROOT_HOME_DIR}"/.config/psysh/config.php;

	if [[ ! -d "${WWW_DATA_HOME_DIR}"/.config ]]; then
		mkdir                                                        "${WWW_DATA_HOME_DIR}"/.config;
		chmod 0700                                                   "${WWW_DATA_HOME_DIR}"/.config;
		chown www-data                                               "${WWW_DATA_HOME_DIR}"/.config;
	fi;
	if [[ ! -d "${WWW_DATA_HOME_DIR}"/.config/psysh ]]; then
		mkdir                                                        "${WWW_DATA_HOME_DIR}"/.config/psysh;
		chmod 0700                                                   "${WWW_DATA_HOME_DIR}"/.config/psysh;
		chown www-data                                               "${WWW_DATA_HOME_DIR}"/.config/psysh;
	fi;
	cp    --preserve=all "${ROOT_HOME_DIR}"/.config/psysh/config.php "${WWW_DATA_HOME_DIR}"/.config/psysh/config.php;
	chown www-data                                                   "${WWW_DATA_HOME_DIR}"/.config/psysh/config.php;

	# -----------------------------------------------------------------------------------------------------------------
	# Install WP-CLI.
	# -----------------------------------------------------------------------------------------------------------------

	curl --location https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar \
		--output /usr/local/bin/wp;
	chmod +x /usr/local/bin/wp;

	if [[ ! -d "${ROOT_HOME_DIR}"/.wp-cli ]]; then
		mkdir                                                  "${ROOT_HOME_DIR}"/.wp-cli;
		chmod 0700                                             "${ROOT_HOME_DIR}"/.wp-cli;
	fi;
	echo "path: ${WORDPRESS_DIR}"                            > "${ROOT_HOME_DIR}"/.wp-cli/config.yml;
	chmod 0600                                                 "${ROOT_HOME_DIR}"/.wp-cli/config.yml;

	if [[ ! -d "${WWW_DATA_HOME_DIR}"/.wp-cli ]]; then
		mkdir                                                  "${WWW_DATA_HOME_DIR}"/.wp-cli;
		chmod 0700                                             "${WWW_DATA_HOME_DIR}"/.wp-cli;
		chown www-data                                         "${WWW_DATA_HOME_DIR}"/.wp-cli;
	fi;
	cp    --preserve=all "${ROOT_HOME_DIR}"/.wp-cli/config.yml "${WWW_DATA_HOME_DIR}"/.wp-cli/config.yml;
	chown www-data                                             "${WWW_DATA_HOME_DIR}"/.wp-cli/config.yml;

	# -----------------------------------------------------------------------------------------------------------------
	# Fill in a few gaps by adding additional extensions already supported by `docker-php-ext-install`.
	# -----------------------------------------------------------------------------------------------------------------

	docker-php-ext-install pdo pdo_mysql pcntl gettext calendar;
	apt-get install libffi-dev --yes && docker-php-ext-install ffi;

	# -----------------------------------------------------------------------------------------------------------------
	# Maybe PECL install igbinary and Memcached extensions.
	# -----------------------------------------------------------------------------------------------------------------
	# We're running Memcached using a Docker container.
	# However, we still need the PHP extension.

	pecl install igbinary-3.2.7;
	docker-php-ext-enable igbinary;

	apt-get install zlib1g-dev --yes;
	apt-get install libmemcached-dev --yes;

	apt-get install expect --yes;
	echo -e "\n\n\nyes\n\n\n\n\n\n" | pecl install memcached-3.1.5;
	docker-php-ext-enable memcached;

	# -----------------------------------------------------------------------------------------------------------------
	# Cleanup.
	# -----------------------------------------------------------------------------------------------------------------

	rm --recursive --force /var/www/html/*;
	rm --force /var/www/html/.htaccess;

	# -----------------------------------------------------------------------------------------------------------------
	# Leave `/usr/src/wordpress`. It's required by our parent image.
	# Leave `/wp-docker/image/setup`. We use it to detect WP docker containers.
	# Do not add or remove anything in `/usr/local`. That's for eventual image consumers.
fi;
# ---------------------------------------------------------------------------------------------------------------------
# Start Apache.
# ---------------------------------------------------------------------------------------------------------------------

apache2-foreground;
