#!/usr/bin/env bash

function c10n-slack-notify() {
	if [[ "${1:-}" =~ ^[A-Za-z0-9_\-]+\= ]]; then
		local "${@}"; # Named args.
	fi;
	local channel="${channel:-C035W9DQNN4}";
	local icon_emoji="${icon_emoji:-foxbot}";
	local text="$(esc-json-str "${text:-"${1:-}"}")";
	local token="${token:-"${2:-}"}";

	curl --request POST \
		--header 'Authorization: Bearer '"${token}" \
		--header 'Content-Type: application/json; charset=utf-8' \
		--data '{ "channel": "'"${channel}"'", "icon_emoji": ":'"${icon_emoji}"':", "text": "'"${text}"'", "parse": "none", "mrkdwn": true }' \
		https://slack.com/api/chat.postMessage;
};
