#!/usr/bin/env bash

# New line.

function chalk-new-line() { echo; };

# Default color.

function chalk-output() { echo -e "${1:-}"; };

# Heading color.

function chalk-heading() {
	if is-chalk-on-dark-bg; then
		echo -e "\e[38;5;212m\e[1m${1:-}\e[0m\e[39m";
	else
		echo -e "\e[38;5;132m\e[1m${1:-}\e[0m\e[39m";
	fi;
};
# Dimmed color for verbose details.

function chalk-log() {
	if is-chalk-on-dark-bg; then
		echo -e "\e[38;5;255m\e[2m${1:-}\e[0m\e[39m";
	else
		echo -e "\e[38;5;232m\e[2m${1:-}\e[0m\e[39m";
	fi;
};
# Colorized output inspired by Bootstrap alerts: `info|warning|danger|success`.
# Hilite variants use a background instead, behind white text to grab extra attention.

# Note: `info` = blue, `warning` = orange, `danger` = red, `success` = green.
# {@see https://getbootstrap.com/docs/4.0/components/alerts/}.

function chalk-info() {
	if is-chalk-on-dark-bg; then
		echo -e "\e[38;5;39m\e[1m${1:-}\e[0m\e[39m";
	else
		echo -e "\e[38;5;26m\e[1m${1:-}\e[0m\e[39m";
	fi;
};
function chalk-info-hilite() {
	echo -e "\e[38;5;255m\e[48;5;26m\e[1m${1:-}\e[0m\e[49m\e[39m";
};

function chalk-warning() {
	if is-chalk-on-dark-bg; then
		echo -e "\e[38;5;214m\e[1m${1:-}\e[0m\e[39m";
	else
		echo -e "\e[38;5;130m\e[1m${1:-}\e[0m\e[39m";
	fi;
};
function chalk-warning-hilite() {
	echo -e "\e[38;5;255m\e[48;5;130m\e[1m${1:-}\e[0m\e[49m\e[39m";
};

function chalk-danger() {
	if is-chalk-on-dark-bg; then
		echo -e "\e[38;5;203m\e[1m${1:-}\e[0m\e[39m";
	else
		echo -e "\e[38;5;124m\e[1m${1:-}\e[0m\e[39m";
	fi;
};
function chalk-danger-hilite() {
	echo -e "\e[38;5;255m\e[48;5;124m\e[1m${1:-}\e[0m\e[49m\e[39m";
};

function chalk-success() {
	if is-chalk-on-dark-bg; then
		echo -e "\e[38;5;41m\e[1m${1:-}\e[0m\e[39m";
	else
		echo -e "\e[38;5;28m\e[1m${1:-}\e[0m\e[39m";
	fi;
};
function chalk-success-hilite() {
	echo -e "\e[38;5;255m\e[48;5;28m\e[1m${1:-}\e[0m\e[49m\e[39m";
};
# Determines whether to show dark|light background variants.
# {@see https://o5p.me/BAkbEq} for inspiration.

function is-chalk-on-dark-bg() { # @todo This needs more work in the future.
	if [[ -z "${COLORFGBG:-}" || "${COLORFGBG}" == '15;0' || "${COLORFGBG}" == '15;default;0' ]]; then
		return 0; # {@see https://o5p.me/BAkbEq}.
	else
		return 1;
	fi;
};
# For testing.

# chalk-heading 'chalk-heading';
# chalk-output 'chalk-output';
# chalk-log 'chalk-log';
# chalk-output
# chalk-info 'chalk-info';
# chalk-warning 'chalk-warning';
# chalk-danger 'chalk-danger';
# chalk-success 'chalk-success';
# chalk-output
# chalk-info-hilite 'chalk-info-hililte';
# chalk-warning-hilite 'chalk-warning-hililte';
# chalk-danger-hilite 'chalk-danger-hililte';
# chalk-success-hilite 'chalk-success-hililte';
