#!/usr/bin/env bash

function confirm() {
	local question="${1:-}";

	if [[ -z "${question}" ]]; then
		question='Are you sure?';
	fi;
	read -p "${question}"' [y|n] ' -n 1 -r;

	if [[ "${REPLY:-}" =~ ^[Yy]$ ]]; then
		return 0; # Yes.
	else
		return 1; # No.
	fi;
}
