/**
 * MDX config file.
 *
 * MDX is not aware of this config file's location.
 *
 * @note PLEASE DO NOT EDIT THIS FILE!
 * @note This entire file will be updated automatically.
 * @note Instead of editing here, please review <https://github.com/clevercanyon/skeleton>.
 *
 * @see https://mdxjs.com/packages/mdx/#api
 */

import extensions from '../bin/includes/extensions.mjs';
import pluginAnchorsPreactXHash from '../rehype/plugins/anchors/preact-x-hash.mjs';
import pluginAnchorsRelExternalNoFollow from '../rehype/plugins/anchors/rel-external-nofollow.mjs';
import pluginFootnotesFixAnchors from '../rehype/plugins/footnotes/fix-anchors.mjs';
import pluginFootnotesFixLabelSection from '../rehype/plugins/footnotes/fix-label-section.mjs';

/**
 * Defines MDX configuration.
 */
export default async () => {
    /**
     * Composition.
     */
    return {
        jsxImportSource: 'preact',

        mdExtensions: [...extensions.byVSCodeLang.markdown],
        mdxExtensions: [...extensions.byVSCodeLang.mdx],

        remarkPlugins: [
            (await import('remark-frontmatter')).default, // Frontmatter.
            [(await import('remark-mdx-frontmatter')).default, { name: 'frontMatter' }],
            [(await import('remark-gfm')).default, { singleTilde: false }], // GFM features.
            (await import('remark-gemoji')).default, // GFM-style emojis using `:shortcodes:`.
            (await import('remark-smartypants')).default, // (em dash) `--` to `—`, quotes, etc.
            (await import('remark-directive')).default, // Custom directives; {@see https://o5p.me/0fakce}.
            [(await import('remark-toc')).default, { heading: 'Table of Contents', prefix: '~' }], // TOC; {@see https://o5p.me/Y8DLuN}.
        ],
        rehypePlugins: [
            pluginFootnotesFixAnchors, // Modifies `remark-gfm` footnote anchors to enforce a `~` prefix.
            pluginFootnotesFixLabelSection, // Modifies `#footnote-label` section at bottom, generated by `remark-gfm` plugin.
            [(await import('rehype-slug')).default, { prefix: '~' }], // Auto-generates heading IDs using heading text and counters.
            [(await import('rehype-autolink-headings')).default, { content: { type: 'text', value: '#' } }], // Auto-links all headings.
            pluginAnchorsPreactXHash, // Modifies hash-only anchors so they work well with `<base href>` in our preact apps.
            pluginAnchorsRelExternalNoFollow, // Modifies external anchors by adding `rel` attribute for improved SEO.
            (await import('@microflash/rehype-starry-night')).default, // Applies syntax highlighting to fenced code blocks.
        ],
        vsCodeTSConfig: {
            plugins: [
                'remark-frontmatter', // Frontmatter.
                ['remark-mdx-frontmatter', { name: 'frontMatter' }],
                ['remark-gfm', { singleTilde: false }], // GFM features.
                'remark-gemoji', // GFM-style emojis using `:shortcodes:`.
                'remark-smartypants', // (em dash) `--` to `—`, quotes, etc.
                'remark-directive', // Custom directives; {@see https://o5p.me/0fakce}.
                ['remark-toc', { heading: 'Table of Contents', prefix: '~' }], // TOC; {@see https://o5p.me/Y8DLuN}.
            ],
        },
    };
};
