/**
 * Stylelint config file.
 *
 * @since 1.0.0
 *
 * @note Stylelint is not aware of this config file's location.
 *       Please extend this file using `../../../.stylelintrc.cjs`.
 *
 * @see https://stylelint.io/user-guide/configure
 *
 * @note PLEASE DO NOT EDIT THIS FILE!
 * This file and the contents of it are updated automatically.
 * - Instead of editing this file, please review source repository {@see https://o5p.me/LevQOD}.
 */
/* eslint-env es2021, node */

module.exports = {
	plugins   : [ 'stylelint-scss' ],
	extends   : [
		'stylelint-config-standard',
		'stylelint-config-html',
		'stylelint-no-unsupported-browser-features',
		'stylelint-config-recess-order',
		'stylelint-config-prettier',
	],
	rules     : {
		indentation                 : 'tab',
		'no-duplicate-selectors'    : false,
		'selector-type-no-unknown'  : false,
		'no-descending-specificity' : false,
		'selector-class-pattern'    : '^[_-]?[a-z][a-z0-9]*(?:[_-]{1,2}[a-z0-9]+)*$',
		'selector-id-pattern'       : '^[a-z][a-z0-9]*(?:[_-]{1,2}[a-z0-9]+)*$',
		'at-rule-no-unknown'        : [
			true,
			{
				ignoreAtRules : [
					'tailwind',
					'apply',
					'variants',
					'responsive',
					'screen',
				],
			},
		],
	},
	overrides : [
		{
			files        : [ '*.css', '**/*.css' ],
			customSyntax : 'postcss-safe-parser',
		},
		{
			files        : [ '*.scss', '**/*.scss' ],
			customSyntax : 'postcss-scss',
		},
		{
			files        : [ '*.{xml,html}', '**/*.{xml,html}' ],
			customSyntax : 'postcss-html',
		},
	],
};
