/**
 * No module preload plugin.
 *
 * Vite is not aware of this config file's location.
 *
 * @note PLEASE DO NOT EDIT THIS FILE!
 * @note This entire file will be updated automatically.
 * @note Instead of editing here, please review <https://github.com/clevercanyon/skeleton>.
 *
 * @review It is not clear what the future of `__vitePreload` will be. At this time, we are leaving this plugin in place,
 * because the use of `__vitePreload` still exists in Vite, but in practice it would seem that `build.modulePreload` is
 * respected better than it used to be. The remaining issue stems from the use of CSS imports, because even when setting
 * `build.modulePreload` to `false`, CSS imports use the same underlying mechanism in Vite, and so they end up
 * triggering `__vitePreload` anyway. However, in Vite 6 it seems that when setting `build.modulePreload` to `false`,
 * Vite strips all CSS imports in order to honor the `build.modulePreload` request.
 */

/**
 * Configures no module preload plugin.
 *
 * @param   props Props from vite config file driver.
 *
 * @returns       No module preload plugin.
 */
export default async (/* {} */) => {
    const virtualId = 'vite/preload-helper.js';
    const resolvedVirtualId = '\0' + virtualId;

    return {
        name: 'vite-plugin-c10n-no-module-preload',
        enforce: 'pre', // Before Vite loads this virtual module.
        // {@see https://vite.dev/guide/using-plugins.html#enforcing-plugin-ordering}.
        // {@see https://vite.dev/guide/api-plugin.html#plugin-ordering}.

        load(id) {
            if (id === resolvedVirtualId) {
                return 'export const __vitePreload = (dynamicImport) => dynamicImport();';
            }
        },
    };
};
