#!/usr/bin/env bash
# shellcheck disable=SC2129,SC2016
##
# Clever Canyon™ {@see https://clevercanyon.com}
#
#  CCCCC  LL      EEEEEEE VV     VV EEEEEEE RRRRRR      CCCCC    AAA   NN   NN YY   YY  OOOOO  NN   NN ™
# CC      LL      EE      VV     VV EE      RR   RR    CC       AAAAA  NNN  NN YY   YY OO   OO NNN  NN
# CC      LL      EEEEE    VV   VV  EEEEE   RRRRRR     CC      AA   AA NN N NN  YYYYY  OO   OO NN N NN
# CC      LL      EE        VV VV   EE      RR  RR     CC      AAAAAAA NN  NNN   YYY   OO   OO NN  NNN
#  CCCCC  LLLLLLL EEEEEEE    VVV    EEEEEEE RR   RR     CCCCC  AA   AA NN   NN   YYY    OOOO0  NN   NN
##

##
# WP docker image setup.
#
# @since 1.0.0
#
# @note PLEASE DO NOT EDIT THIS FILE!
# This file and the contents of it are updated automatically.
# Instead of editing this file, please edit `./dev/.libs/docker/wp/compose~prj.yml`.
#
# @todo Add MySQL permissions that allow for additional databases to be created.
# @todo Install the PHP SOAP extension for WooCommerce.
##

# ---------------------------------------------------------------------------------------------------------------------
# Source a few dependencies.
# ---------------------------------------------------------------------------------------------------------------------

. /wp-docker/host/project/dev/utilities/load.bash;
. /wp-docker/host/project/dev/utilities/bash/partials/require-root.bash;

# ---------------------------------------------------------------------------------------------------------------------
# Define a few variables.
# ---------------------------------------------------------------------------------------------------------------------

WP_DOCKER_ROOT_HOME_DIR=/root;                # `root` user’s home directory.
WP_DOCKER_WEB_SERVER_USER=www-data;           # Web server runs as user `www-data`.
WP_DOCKER_WEB_SERVER_USER_HOME_DIR=/var/www;  # Web server user’s home directory.
WP_DOCKER_WORDPRESS_DIR=/var/www/html;        # Apache `DOCUMENT_ROOT` directory.

# ---------------------------------------------------------------------------------------------------------------------
# Run parent container's entrypoint before we continue.
# The `apache2-noop` name is important. Noting because it's extremely non-obvious.
# Take a peek at the top of `docker-entrypoint.sh` to see why `apache2` is key; {@see https://o5p.me/j70ja4}.
# ---------------------------------------------------------------------------------------------------------------------

if [[ ! -f /usr/bin/apache2-noop ]]; then
	echo '#!/usr/bin/env bash' > /usr/bin/apache2-noop;
	chmod +x /usr/bin/apache2-noop;
fi;
/usr/local/bin/docker-entrypoint.sh apache2-noop;

# ---------------------------------------------------------------------------------------------------------------------
# Maybe run setup routines.
# ---------------------------------------------------------------------------------------------------------------------

if [[ ! -f /wp-docker/image/setup-complete ]]; then
	mkdir --parents /wp-docker/image;
	touch /wp-docker/image/setup-complete;

	# -----------------------------------------------------------------------------------------------------------------
	# Aptitude.
	# -----------------------------------------------------------------------------------------------------------------

	apt-get update --yes;

	# -----------------------------------------------------------------------------------------------------------------
	# Core utilities.
	# -----------------------------------------------------------------------------------------------------------------

	apt-get install man --yes;
	apt-get install coreutils --yes;

	# -----------------------------------------------------------------------------------------------------------------
	# Build tools.
	# -----------------------------------------------------------------------------------------------------------------

	apt-get install build-essential --yes;
	apt-get install g++ --yes;
	apt-get install cmake --yes;
	apt-get install expect --yes;
	apt-get install libtool --yes;
	apt-get install autoconf --yes;
	apt-get install pkg-config --yes;

	# -----------------------------------------------------------------------------------------------------------------
	# Other tools; grouped broadly by function.
	# -----------------------------------------------------------------------------------------------------------------

	apt-get install tar zip gzip unzip --yes;
	apt-get install curl wget rsync --yes;
	apt-get install telnet netcat --yes;
	apt-get install openssl gpg --yes;
	apt-get install tmux screen --yes;
	apt-get install tree ack grok less --yes;
	apt-get install gettext pandoc --yes;
	apt-get install vim nano --yes;
	apt-get install ncdu htop --yes;
	apt-get install sudo acl pwgen --yes;
	apt-get install apache2-utils mailutils --yes;
	apt-get install perl ruby python3 nodejs golang-go --yes;
	apt-get install git subversion npm --yes; # After nodejs.

	# -----------------------------------------------------------------------------------------------------------------
	# Give web server user a default login shell; and write access to its own HOME directory.
	# -----------------------------------------------------------------------------------------------------------------

	chsh  --shell /bin/bash                          "${WP_DOCKER_WEB_SERVER_USER}";
	chmod --recursive 0700                           "${WP_DOCKER_WEB_SERVER_USER_HOME_DIR}";
	chown --recursive "${WP_DOCKER_WEB_SERVER_USER}" "${WP_DOCKER_WEB_SERVER_USER_HOME_DIR}";

	# -----------------------------------------------------------------------------------------------------------------
	# Fill in gaps by enabling additional Apache modules.
	# -----------------------------------------------------------------------------------------------------------------

	a2enmod headers; # Needed by `.htaccess` for our own sites.

	# -----------------------------------------------------------------------------------------------------------------
	# Simple shell enhancements.
	# -----------------------------------------------------------------------------------------------------------------

	apt-get install bash-completion --yes;

	rm    --force                                              "${WP_DOCKER_ROOT_HOME_DIR}"/.bashrc;
	touch                                                      "${WP_DOCKER_ROOT_HOME_DIR}"/.profile;
	chmod 0600                                                 "${WP_DOCKER_ROOT_HOME_DIR}"/.profile;

	{   echo 'export PS1="🐳 \[\e[32m\]\h\[\e[m\] \[\e[34m\][\[\e[m\]\[\e[33m\]\w\[\e[m\]\[\e[34m\]]\[\e[m\] \\$ ";';

		echo "alias ls='ls -la --color=auto';";

		echo 'function cd() { builtin cd "${@}" && ls; };';
		echo 'function up() { cd ../ || return 1; };';
		echo 'function back() { cd - || return 1; };';
		echo 'function home() { cd ~/ || return 1; };';

		echo 'if [ -f /etc/bash_completion ]; then';
		echo '	. /etc/bash_completion;';
		echo 'fi;';
	} >> "${WP_DOCKER_ROOT_HOME_DIR}"/.profile;

	cp    --preserve=all "${WP_DOCKER_ROOT_HOME_DIR}"/.profile "${WP_DOCKER_WEB_SERVER_USER_HOME_DIR}"/.profile;
	chown "${WP_DOCKER_WEB_SERVER_USER}"                       "${WP_DOCKER_WEB_SERVER_USER_HOME_DIR}"/.profile;

	# -----------------------------------------------------------------------------------------------------------------
	# Install Composer.
	# -----------------------------------------------------------------------------------------------------------------

	curl --location https://getcomposer.org/installer \
		 | php -- --install-dir=/usr/local/bin --filename=composer;

	# -----------------------------------------------------------------------------------------------------------------
	# Install PHPUnit.
	# -----------------------------------------------------------------------------------------------------------------

	curl --location https://phar.phpunit.de/phpunit.phar \
		 --output /usr/local/bin/phpunit;
	chmod +x /usr/local/bin/phpunit;

	# -----------------------------------------------------------------------------------------------------------------
	# Install Psysh.
	# -----------------------------------------------------------------------------------------------------------------

	curl --location https://psysh.org/psysh \
		 --output /usr/local/bin/psysh;
	chmod +x /usr/local/bin/psysh;

	if [[ ! -d "${WP_DOCKER_ROOT_HOME_DIR}"/.config ]]; then
		mkdir      "${WP_DOCKER_ROOT_HOME_DIR}"/.config;
		chmod 0700 "${WP_DOCKER_ROOT_HOME_DIR}"/.config;
	fi;
	if [[ ! -d "${WP_DOCKER_ROOT_HOME_DIR}"/.config/psysh ]]; then
		mkdir      "${WP_DOCKER_ROOT_HOME_DIR}"/.config/psysh;
		chmod 0700 "${WP_DOCKER_ROOT_HOME_DIR}"/.config/psysh;
	fi;
	{   echo '<?php';
		echo 'use Clever_Canyon\{Utilities as U};';
		echo "if ( is_file( '/wp-docker/host/project/vendor/autoload.php' ) ) {";
		echo "    require_once '/wp-docker/host/project/vendor/autoload.php';";
		echo "    U\\Env::set_debug_mode( 'psysh' );";
		echo '}';
		echo 'return [];';
	} > "${WP_DOCKER_ROOT_HOME_DIR}"/.config/psysh/config.php;
	chmod 0600 "${WP_DOCKER_ROOT_HOME_DIR}"/.config/psysh/config.php;

	if [[ ! -d "${WP_DOCKER_WEB_SERVER_USER_HOME_DIR}"/.config ]]; then
		mkdir                                                                  "${WP_DOCKER_WEB_SERVER_USER_HOME_DIR}"/.config;
		chmod 0700                                                             "${WP_DOCKER_WEB_SERVER_USER_HOME_DIR}"/.config;
		chown "${WP_DOCKER_WEB_SERVER_USER}"                                   "${WP_DOCKER_WEB_SERVER_USER_HOME_DIR}"/.config;
	fi;
	if [[ ! -d "${WP_DOCKER_WEB_SERVER_USER_HOME_DIR}"/.config/psysh ]]; then
		mkdir                                                                  "${WP_DOCKER_WEB_SERVER_USER_HOME_DIR}"/.config/psysh;
		chmod 0700                                                             "${WP_DOCKER_WEB_SERVER_USER_HOME_DIR}"/.config/psysh;
		chown "${WP_DOCKER_WEB_SERVER_USER}"                                   "${WP_DOCKER_WEB_SERVER_USER_HOME_DIR}"/.config/psysh;
	fi;
	cp    --preserve=all "${WP_DOCKER_ROOT_HOME_DIR}"/.config/psysh/config.php "${WP_DOCKER_WEB_SERVER_USER_HOME_DIR}"/.config/psysh/config.php;
	chown "${WP_DOCKER_WEB_SERVER_USER}"                                       "${WP_DOCKER_WEB_SERVER_USER_HOME_DIR}"/.config/psysh/config.php;

	# -----------------------------------------------------------------------------------------------------------------
	# Install WP-CLI.
	# -----------------------------------------------------------------------------------------------------------------

	curl --location https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar \
		--output /usr/local/bin/wp;
	chmod +x /usr/local/bin/wp;

	if [[ ! -d "${WP_DOCKER_ROOT_HOME_DIR}"/.wp-cli ]]; then
		mkdir                                                            "${WP_DOCKER_ROOT_HOME_DIR}"/.wp-cli;
		chmod 0700                                                       "${WP_DOCKER_ROOT_HOME_DIR}"/.wp-cli;
	fi;
	echo "path: ${WP_DOCKER_WORDPRESS_DIR}"                            > "${WP_DOCKER_ROOT_HOME_DIR}"/.wp-cli/config.yml;
	chmod 0600                                                           "${WP_DOCKER_ROOT_HOME_DIR}"/.wp-cli/config.yml;

	if [[ ! -d "${WP_DOCKER_WEB_SERVER_USER_HOME_DIR}"/.wp-cli ]]; then
		mkdir                                                            "${WP_DOCKER_WEB_SERVER_USER_HOME_DIR}"/.wp-cli;
		chmod 0700                                                       "${WP_DOCKER_WEB_SERVER_USER_HOME_DIR}"/.wp-cli;
		chown "${WP_DOCKER_WEB_SERVER_USER}"                             "${WP_DOCKER_WEB_SERVER_USER_HOME_DIR}"/.wp-cli;
	fi;
	cp    --preserve=all "${WP_DOCKER_ROOT_HOME_DIR}"/.wp-cli/config.yml "${WP_DOCKER_WEB_SERVER_USER_HOME_DIR}"/.wp-cli/config.yml;
	chown "${WP_DOCKER_WEB_SERVER_USER}"                                 "${WP_DOCKER_WEB_SERVER_USER_HOME_DIR}"/.wp-cli/config.yml;

	# -----------------------------------------------------------------------------------------------------------------
	# Install MailHog's MTA for SMTP connectivity.
	# -----------------------------------------------------------------------------------------------------------------

	go get github.com/mailhog/mhsendmail; # MailHog.
	ln --symbolic ~/go/bin/mhsendmail /usr/bin/mhsendmail;
	echo 'sendmail_path = /usr/bin/mhsendmail --smtp-addr hog:1025' \
		> /usr/local/etc/php/conf.d/mailhog.ini;

	# -----------------------------------------------------------------------------------------------------------------
	# Fill in a few gaps by adding additional extensions already supported by `docker-php-ext-install`.
	# -----------------------------------------------------------------------------------------------------------------

	docker-php-ext-install pdo pdo_mysql pcntl gettext calendar;
	apt-get install libffi-dev --yes && docker-php-ext-install ffi;
	apt-get install libxml2-dev --yes && docker-php-ext-install soap;

	# -----------------------------------------------------------------------------------------------------------------
	# Maybe PECL install igbinary and Memcached extensions.
	# -----------------------------------------------------------------------------------------------------------------
	# We're running Memcached using a Docker container.
	# However, we still need the PHP extension.

	pecl install igbinary-3.2.7;
	docker-php-ext-enable igbinary;

	apt-get install zlib1g-dev --yes;
	apt-get install libmemcached-dev --yes;

	apt-get install expect --yes;
	echo -e "\n\n\nyes\n\n\n\n\n\n" | pecl install memcached-3.1.5;
	docker-php-ext-enable memcached;

	# -----------------------------------------------------------------------------------------------------------------
	# Cleanup.
	# -----------------------------------------------------------------------------------------------------------------

	rm --recursive --force /var/www/html/*;
	rm --force /var/www/html/.htaccess;

	# -----------------------------------------------------------------------------------------------------------------
	# Leave `/usr/src/wordpress`. It's required by our parent image.
	# Leave `/wp-docker/image/setup`. We use it to detect WP docker containers.
	# Do not add or remove anything in `/usr/local`. That's for eventual image consumers.
fi;
