#!/usr/bin/env bash
# shellcheck disable=SC2129,SC2016
##
# WP docker image setup.
#
# @since 1.0.0
#
# @note PLEASE DO NOT EDIT THIS FILE!
# This file and the contents of it are updated automatically.
# Instead of editing this file, please edit `./.wp-docker.prj.sh`.
##
# ---------------------------------------------------------------------------------------------------------------------
# Image Setup Instructions:
# ---------------------------------------------------------------------------------------------------------------------
# Parent Images:
# - wordpress:php8.1-apache
# - wordpress:php8.0-apache
# - wordpress:php7.4-apache
#
# WP Docker Images:
# - jaswrks/wp-docker:php8.1-apache
# - jaswrks/wp-docker:php8.0-apache
# - jaswrks/wp-docker:php7.4-apache
#
# - Start a new container with each of the parent images; e.g., using Docker Desktop.
# - Log into each container and install `vim`: `$ apt-get update --yes && apt-get install vim --yes;`.
# - Create a new file: `$ vi /usr/local/src/x-.wp-docker.is.sh`. Paste the contents of this file in and save.
# - Run `chmod +x /usr/local/src/x-.wp-docker.is.sh && /usr/local/src/x-.wp-docker.is.sh` ... await completion.
# - Commit the image: `$ docker commit [container-name] jaswrks/wp-docker:php[version]-apache`.
# - Push the image to Docker Hub: `$ docker push jaswrks/wp-docker:php[version]-apache`.
# ---------------------------------------------------------------------------------------------------------------------

# ---------------------------------------------------------------------------------------------------------------------
# Guard against mishaps. Must run inside a container only.
# ---------------------------------------------------------------------------------------------------------------------

if [[ ! -f /.dockerenv \
	|| "$(whoami)" != 'root' ]]; then
	echo 'No direct access.'; exit 1;
fi;
# ---------------------------------------------------------------------------------------------------------------------
# Strict mode and shell options.
# ---------------------------------------------------------------------------------------------------------------------

set   -o nounset; set   -o errexit; set   -o errtrace; set   -o pipefail;
shopt -s extglob; shopt -s dotglob; shopt -s globstar; shopt -s nullglob;

# ---------------------------------------------------------------------------------------------------------------------
# Stack trace handler.
# ---------------------------------------------------------------------------------------------------------------------

function stack_trace() {
  local last_command_status_code=$?;
  set +o xtrace; # {@see https://o5p.me/8eGn9c}.
  local exit_status_code="${1:-1}";

  echo '----------------------------------------------------------------------';
  echo 'Error in '"${BASH_SOURCE[1]}"':'"${BASH_LINENO[0]}";
  echo '`'"${BASH_COMMAND}"'` exited with status `'"${last_command_status_code}"'`.';

  if [[ ${#FUNCNAME[@]} -gt 2 ]]; then
    echo 'Stack Trace:';
    for ((_i=1; _i < ${#FUNCNAME[@]}-1; _i++)); do
      echo " ${_i}: ${BASH_SOURCE[${_i}+1]}:${BASH_LINENO[${_i}]} ${FUNCNAME[${_i}]}(...)";
    done;
  fi;
  echo 'Exiting w/ status `'"${exit_status_code}"'`.'; exit "${exit_status_code}";
};
trap stack_trace ERR;

# ---------------------------------------------------------------------------------------------------------------------
# Version compare utility function.
# ---------------------------------------------------------------------------------------------------------------------

function version-compare() {
  local v1="'${1:-}'"; local v2="'${2:-}'"; local op="'${3:-}'";
  if [[ "$(php -r 'echo (int)version_compare('"${v1}"', '"${v2}"', '"${op}"');')" == 1 ]];
  	then return 0; else return 1; fi;
};

# ---------------------------------------------------------------------------------------------------------------------
# Define a few variables.
# ---------------------------------------------------------------------------------------------------------------------

ROOT_HOME_DIR=/root;         # `root` user's home directory.
WWW_DATA_HOME_DIR=/var/www;  # `www-data` user's home directory.
WORDPRESS_DIR=/var/www/html; # Apache `DOCUMENT_ROOT` directory.

# -----------------------------------------------------------------------------------------------------------------
# Aptitude.
# -----------------------------------------------------------------------------------------------------------------

apt-get update --yes;

# -----------------------------------------------------------------------------------------------------------------
# Core utilities.
# -----------------------------------------------------------------------------------------------------------------

apt-get install man --yes;
apt-get install coreutils --yes;

# -----------------------------------------------------------------------------------------------------------------
# Build tools.
# -----------------------------------------------------------------------------------------------------------------

apt-get install build-essential --yes;
apt-get install g++ --yes;
apt-get install cmake --yes;
apt-get install expect --yes;
apt-get install libtool --yes;
apt-get install autoconf --yes;
apt-get install pkg-config --yes;

# -----------------------------------------------------------------------------------------------------------------
# Other tools; grouped broadly by function.
# -----------------------------------------------------------------------------------------------------------------

apt-get install tar zip gzip unzip --yes;
apt-get install curl wget rsync --yes;
apt-get install telnet netcat --yes;
apt-get install openssl gpg --yes;
apt-get install tmux screen --yes;
apt-get install tree ack grok less --yes;
apt-get install gettext pandoc --yes;
apt-get install vim nano --yes;
apt-get install ncdu htop --yes;
apt-get install acl pwgen --yes;
apt-get install apache2-utils --yes;
apt-get install git subversion --yes;
apt-get install perl ruby python3 --yes;
apt-get install nodejs npm --yes;

# -----------------------------------------------------------------------------------------------------------------
# `www-data` should have write access to its own HOME directory.
# -----------------------------------------------------------------------------------------------------------------

chmod 0700                                            "${WWW_DATA_HOME_DIR}";
chown --recursive www-data                            "${WWW_DATA_HOME_DIR}";

# -----------------------------------------------------------------------------------------------------------------
# Simple shell enhancements.
# -----------------------------------------------------------------------------------------------------------------

apt-get install bash-completion --yes;

rm --force                                            "${ROOT_HOME_DIR}"/.bashrc;
touch                                                 "${ROOT_HOME_DIR}"/.profile;
chmod 0600                                            "${ROOT_HOME_DIR}"/.profile;

echo 'export PS1="🐳 \[\e[32m\]\h\[\e[m\] \[\e[34m\][\[\e[m\]\[\e[33m\]\w\[\e[m\]\[\e[34m\]]\[\e[m\] \\$ ";' \
												   >> "${ROOT_HOME_DIR}"/.profile;

echo 'alias ls='"'"'ls -la --color=auto'"'"';'     >> "${ROOT_HOME_DIR}"/.profile;
echo 'function cd() { builtin cd "${@}" && ls; };' >> "${ROOT_HOME_DIR}"/.profile;
echo 'function up() { cd ../ || return 1; };'      >> "${ROOT_HOME_DIR}"/.profile;
echo 'function back() { cd - || return 1; };'      >> "${ROOT_HOME_DIR}"/.profile;
echo 'function home() { cd ~/ || return 1; };'     >> "${ROOT_HOME_DIR}"/.profile;

echo 'if [ -f /etc/bash_completion ]; then'        >> "${ROOT_HOME_DIR}"/.profile;
echo '	. /etc/bash_completion;'                   >> "${ROOT_HOME_DIR}"/.profile;
echo 'fi;'                                         >> "${ROOT_HOME_DIR}"/.profile;

cp --preserve=all "${ROOT_HOME_DIR}"/.profile         "${WWW_DATA_HOME_DIR}"/.profile;
chown www-data                                        "${WWW_DATA_HOME_DIR}"/.profile;

# -----------------------------------------------------------------------------------------------------------------
# Install Composer.
# -----------------------------------------------------------------------------------------------------------------

curl --location https://getcomposer.org/installer \
	| php -- --install-dir=/usr/local/bin --filename=composer;

# -----------------------------------------------------------------------------------------------------------------
# Install PHPUnit.
# -----------------------------------------------------------------------------------------------------------------

curl --location https://phar.phpunit.de/phpunit.phar \
	--output /usr/local/bin/phpunit;
chmod +x /usr/local/bin/phpunit;

# -----------------------------------------------------------------------------------------------------------------
# Install Psysh.
# -----------------------------------------------------------------------------------------------------------------

curl --location https://psysh.org/psysh \
	--output /usr/local/bin/psysh;
chmod +x /usr/local/bin/psysh;

mkdir --parents                                                    "${ROOT_HOME_DIR}"/.config/psysh;
echo '<?php'                                                     > "${ROOT_HOME_DIR}"/.config/psysh/config.php;
echo "if ( is_file( '/x-host/project/vendor/autoload.php' ) )"  >> "${ROOT_HOME_DIR}"/.config/psysh/config.php;
echo "    require_once '/x-host/project/vendor/autoload.php';"  >> "${ROOT_HOME_DIR}"/.config/psysh/config.php;
echo 'return [];'                                               >> "${ROOT_HOME_DIR}"/.config/psysh/config.php;

chmod 0700                                                         "${ROOT_HOME_DIR}"/.config;
chmod 0700                                                         "${ROOT_HOME_DIR}"/.config/psysh;
chmod 0600                                                         "${ROOT_HOME_DIR}"/.config/psysh/config.php;

mkdir --parents                                                    "${WWW_DATA_HOME_DIR}"/.config;
chmod 0700                                                         "${WWW_DATA_HOME_DIR}"/.config;
rm --recursive --force                                             "${WWW_DATA_HOME_DIR}"/.config/psysh;
cp --recursive --preserve=all "${ROOT_HOME_DIR}"/.config/psysh     "${WWW_DATA_HOME_DIR}"/.config/psysh;
chown --recursive www-data                                         "${WWW_DATA_HOME_DIR}"/.config;

# -----------------------------------------------------------------------------------------------------------------
# Install WP-CLI.
# -----------------------------------------------------------------------------------------------------------------

curl --location https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar \
	--output /usr/local/bin/wp;
chmod +x /usr/local/bin/wp;

mkdir                                                    "${ROOT_HOME_DIR}"/.wp-cli;
echo "path: ${WORDPRESS_DIR}"               >            "${ROOT_HOME_DIR}"/.wp-cli/config.yml;

chmod 0700                                               "${ROOT_HOME_DIR}"/.wp-cli;
chmod 0600                                               "${ROOT_HOME_DIR}"/.wp-cli/config.yml;

rm --recursive --force                                   "${WWW_DATA_HOME_DIR}"/.wp-cli;
cp --recursive --preserve=all "${ROOT_HOME_DIR}"/.wp-cli "${WWW_DATA_HOME_DIR}"/.wp-cli;
chown --recursive www-data                               "${WWW_DATA_HOME_DIR}"/.wp-cli;

# -----------------------------------------------------------------------------------------------------------------
# Install `info.php` file for debugging.
# -----------------------------------------------------------------------------------------------------------------

echo '<?php phpinfo();' > "${WORDPRESS_DIR}"/info.php;

# -----------------------------------------------------------------------------------------------------------------
# Fill in a few gaps by adding additional extensions already supported by `docker-php-ext-install`.
# -----------------------------------------------------------------------------------------------------------------

docker-php-ext-install pdo pdo_mysql pcntl gettext calendar;
apt-get install libffi-dev --yes && docker-php-ext-install ffi;

# -----------------------------------------------------------------------------------------------------------------
# Maybe PECL install igbinary and Memcached extensions.
# -----------------------------------------------------------------------------------------------------------------

# We're running Memcached using a Docker container.
# However, we still need the PHP extension.

pecl install igbinary-3.2.7;
docker-php-ext-enable igbinary;

apt-get install zlib1g-dev --yes;
apt-get install libmemcached-dev --yes;

apt-get install expect --yes;
echo -e "\n\n\nyes\n\n\n\n\n\n" | pecl install memcached-3.1.5;
docker-php-ext-enable memcached;

# -----------------------------------------------------------------------------------------------------------------
# Reload Apache configuration so extensions kick-in.
# -----------------------------------------------------------------------------------------------------------------

/etc/init.d/apache2 reload;

# -----------------------------------------------------------------------------------------------------------------
# Cleanup.
# -----------------------------------------------------------------------------------------------------------------

rm -rf /var/www/html/* --force;
rm -rf /var/www/html/.htaccess --force;
rm -rf /root/.viminfo --force;

# Be sure to leave `/usr/src/wordpress`, it's required by parent image.
