/**
 * Cssnano config file.
 *
 * @since 1.0.0
 *
 * @note CSSNano doesn't know where this file lives.
 * If you ever need to call cssnano directly be sure to tell it.
 * It's not an issue at this time because we don't call it directly.
 *
 * @internal `assetsDir` is a relative path, as given.
 * @see https://cssnano.co/docs/config-file/
 *
 * @note PLEASE DO NOT EDIT THIS FILE!
 * This file and the contents of it are updated automatically.
 * - Instead of editing this file, please configure `../../../package.json`. See instructions below.
 * - Instead of editing this file, please review source repository {@see https://o5p.me/LevQOD}.
 */
/* eslint-env es2021, node */

/* @formatter:ignore
-----------------------------------------------------------------------------------------------------------------------
Example `config.c10n.&.cssnano` in `../../../package.json`:
-----------------------------------------------------------------------------------------------------------------------
"config"          : {
	"c10n" : {
		"&" : {
			"cssnano" : {
				"config" : {
					"preset" : [ "default", {} ]
				}
			},
			"cssnano:./src": {
				"config" : {}
			}
		}
	}
}
------------------------------------------------------------------------------------------------- @formatter:/ignore */

const path = require( 'path' );
const mc   = require( '@clevercanyon/js-object-mc' );

module.exports = ( srcDir = '' ) => {
	// Initialize global data.

	const globalData = { config : {} };

	// Get custom data by file.

	const customDataByFile = {}; // Initialize.

	try { // Try `package.json` data.
		customDataByFile[ 'package.json' ] = require( '../../../package.json' );
	} catch ( e ) {
		customDataByFile[ 'package.json' ] = {};
	}
	// Merge custom data, that's global, into global data.

	for ( const [ fileName, fileData ] of Object.entries( customDataByFile ) ) {
		switch ( fileName ) {
			case 'package.json':
				mc.patch( globalData, fileData?.config?.c10n?.[ '&' ]?.cssnano || {} );
				break;
		}
	}
	// Now establish a configuration for this src directory.

	const absSrcDir = path.resolve( __dirname, '../../../', srcDir );

	const srcDirConfig = {
		preset : [ 'default', { discardComments : { removeAll : true } } ],
	};
	// Merge custom config data that's global.

	mc.patch( srcDirConfig, globalData.config || {} );

	// Merge custom config data for this src directory.

	for ( const [ fileName, fileData ] of Object.entries( customDataByFile ) ) {
		switch ( fileName ) {
			case 'package.json':
				mc.patch( srcDirConfig, fileData?.config?.c10n?.[ '&' ]?.[ 'cssnano:' + srcDir ]?.config || {} );
				break;
		}
	}
	// Return config.

	return srcDirConfig;
};
