#!/usr/bin/env php
<?php
/**
 * CLEVER CANYON™ {@see https://clevercanyon.com}
 *
 *  CCCCC  LL      EEEEEEE VV     VV EEEEEEE RRRRRR      CCCCC    AAA   NN   NN YY   YY  OOOOO  NN   NN ™
 * CC      LL      EE      VV     VV EE      RR   RR    CC       AAAAA  NNN  NN YY   YY OO   OO NNN  NN
 * CC      LL      EEEEE    VV   VV  EEEEE   RRRRRR     CC      AA   AA NN N NN  YYYYY  OO   OO NN N NN
 * CC      LL      EE        VV VV   EE      RR  RR     CC      AAAAAAA NN  NNN   YYY   OO   OO NN  NNN
 *  CCCCC  LLLLLLL EEEEEEE    VVV    EEEEEEE RR   RR     CCCCC  AA   AA NN   NN   YYY    OOOO0  NN   NN
 */
// <editor-fold desc="Strict types, namespace, use statements, and other headers.">

/**
 * Declarations & namespace.
 *
 * @since 2021-12-25
 */
declare( strict_types = 1 );
namespace Clever_Canyon\Utilities\Dev\CLI_Tools\PHP_Scoper;

/**
 * Utilities.
 *
 * @since 2021-12-15
 */
use Clever_Canyon\{Utilities as U};

// </editor-fold>

/**
 * CLI mode only.
 *
 * @since 2021-12-15
 */
if ( 'cli' !== PHP_SAPI ) {
	exit( 1 ); // CLI mode only.
}

/**
 * Project directory.
 *
 * @since 2021-12-15
 */
$project_dir = require dirname( __FILE__, 2 ) . '/composer/.cli-project-dir.php';

/**
 * Requires autoloader.
 *
 * @since 2021-12-15
 */
require_once $project_dir . '/vendor/autoload.php';

/**
 * Enables debugging mode.
 *
 * @since 2021-12-15
 */
U\Env::config_debugging_mode();

/**
 * CLI tool instance.
 *
 * @since 2021-12-15
 */
new U\Dev\CLI_Tools\PHP_Scoper\Config_File();
