<?php
/**
 * Clever Canyon™ {@see https://clevercanyon.com}
 *
 *  CCCCC  LL      EEEEEEE VV     VV EEEEEEE RRRRRR      CCCCC    AAA   NN   NN YY   YY  OOOOO  NN   NN ™
 * CC      LL      EE      VV     VV EE      RR   RR    CC       AAAAA  NNN  NN YY   YY OO   OO NNN  NN
 * CC      LL      EEEEE    VV   VV  EEEEE   RRRRRR     CC      AA   AA NN N NN  YYYYY  OO   OO NN N NN
 * CC      LL      EE        VV VV   EE      RR  RR     CC      AAAAAAA NN  NNN   YYY   OO   OO NN  NNN
 *  CCCCC  LLLLLLL EEEEEEE    VVV    EEEEEEE RR   RR     CCCCC  AA   AA NN   NN   YYY    OOOO0  NN   NN
 */
// <editor-fold desc="Strict types, namespace, use statements, and other headers.">

/**
 * Lint configuration.
 *
 * @since 2021-12-15
 *
 * phpcs:disable WordPress.NamingConventions.ValidVariableName.UsedPropertyNotSnakeCase
 */

/**
 * Declarations & namespace.
 *
 * @since 2021-12-25
 */
declare( strict_types = 1 );
namespace Clever_Canyon\Utilities\Dev\CLI_Tools\PHP_Scoper;

/**
 * Utilities.
 *
 * @since 2021-12-15
 */
use Clever_Canyon\{Utilities as U};

/**
 * File-specific.
 *
 * @since 2021-12-15
 */
use PhpParser;

// </editor-fold>

/**
 * PHP Scoper config file generator.
 *
 * @since 2021-12-15
 */
final class Config_File extends U\A6t\CLI_Tool {
	/**
	 * Project.
	 *
	 * @since 2021-12-15
	 */
	protected U\Dev\Project $project;

	/**
	 * Version.
	 *
	 * @since 2021-12-15
	 */
	protected const VERSION = '1.0.0';

	/**
	 * Tool name.
	 *
	 * @since 2021-12-15
	 */
	protected const NAME = 'PHP_Scoper/Config_File';

	/**
	 * Constructor.
	 *
	 * @since 2021-12-15
	 *
	 * @param string|array|null $args_to_parse Optional custom args to parse instead of `$_SERVER['argv']`.
	 *                                         If not given, defaults internally to `$_SERVER['argv']`.
	 */
	public function __construct( /* string|array|null */ $args_to_parse = null ) {
		parent::__construct( $args_to_parse );

		$this->add_commands( [
			'update' => [
				'callback'    => [ $this, 'update' ],
				'synopsis'    => 'Updates `src/libraries/dotfiles/.scoper.cfg.php` config file.',
				'description' => 'Updates `src/libraries/dotfiles/.scoper.cfg.php` config file. See ' . __CLASS__ . '::update()',
				'options'     => [
					'project-dir' => [
						'required'    => true,
						'description' => 'Project directory path.',
						'validator'   => fn( $value ) => ( $abs_path = $this->v6e_abs_path( $value, 'dir' ) )
							&& is_file( U\Dir::join( $abs_path, '/composer.json' ) ),
					],
				],
			],
		] );
		$this->route_request();
	}

	/**
	 * Command: `update`.
	 *
	 * @since 2021-12-15
	 */
	protected function update() : void {
		try {
			U\CLI::heading( '[' . __METHOD__ . '()]: Updating ...' );

			$project_dir   = U\Fs::abs( $this->get_option( 'project-dir' ) );
			$this->project = new U\Dev\Project( $project_dir );

			$this->update_file();

			U\CLI::done( '[' . __METHOD__ . '()]: Update complete ✔.' );
		} catch ( \Throwable $throwable ) {
			U\CLI::error( $throwable->getMessage() );
			U\CLI::error( $throwable->getTraceAsString() );
			U\CLI::exit_status( 1 );
		}
	}

	/**
	 * Updates config file.
	 *
	 * @since 2022-01-02
	 *
	 * @throws U\Fatal_Exception On any error.
	 */
	protected function update_file() : void {
		U\CLI::output( '[' . __FUNCTION__ . '()]: Regenerating config file ...' );

		$cfg_file = U\Dir::name( __FILE__, 6, '/dev/libraries/dotfiles/.scoper.cfg.php' );

		if ( ! is_file( $cfg_file ) && ! U\File::make( $cfg_file, [ [ 0755, 0755 ], 0644 ], false, false ) ) {
			throw new U\Fatal_Exception( 'Failed to create PHP Scoper config file: `' . $cfg_file . '`.' );
		}
		if ( ! U\File::write( $cfg_file, $this->generate_config_file_contents(), false ) ) {
			throw new U\Fatal_Exception( 'Failed to update PHP Scoper config file: `' . $cfg_file . '`.' );
		}
		U\CLI::log( '[' . __FUNCTION__ . '()]: Updated: `' . $cfg_file . '`.' );
	}

	/**
	 * Generates config file contents.
	 *
	 * @since 2022-01-02
	 *
	 * @return string Config file contents.
	 */
	protected function generate_config_file_contents() : string {
		U\Env::raise_memory_limit();

		$patchers      = $this->compile_patchers();
		$exclude_files = $this->compile_exclude_files();
		$exclude_names = $this->compile_exclude_names();

		sort( $exclude_names->constants, SORT_NATURAL );
		sort( $exclude_names->classes, SORT_NATURAL );
		sort( $exclude_names->functions, SORT_NATURAL );

		$headers = <<<'ooo'
		<?php
		/**
		 * PHP Scoper config file.
		 *
		 * PHP Scoper doesn't automatically know about this file.
		 * You must pass it explicitly to `php-scoper` using the `--config` option.
		 *
		 * PLEASE DO NOT EDIT THIS FILE!
		 * This file and the contents of it are updated automatically.
		 * Instead of editing, please configure `composer.json`. See instructions below.
		 * Instead of editing, please create `.scoper.prj.cfg.php`, which can also be merged in.
		 * Instead of editing, please review source repository {@see https://o5p.me/LevQOD}.
		 *
		 * @since 1.0.0
		 * @noinspection ALL
		 * phpcs:disableFile
		 */

		/* @formatter:ignore
		-----------------------------------------------------------------------------------------------------------------------
		Example `extra.clevercanyon.&.php_scoper` in `composer.json`:
		-----------------------------------------------------------------------------------------------------------------------
		"extra" : {
			"clevercanyon" : {
				"&" : {
					"php_scoper" : {
						"cfg" : {
							"exclude-files"     : [],
							"exclude-constants" : [],
							"exclude-classes"   : [],
							"exclude-functions" : [],
						}
					}
				}
			}
		}
		------------------------------------------------------------------------------------------------- @formatter:/ignore */

		/**
		 * Declarations & namespace.
		 *
		 * @since 2021-12-15
		 */
		declare( strict_types = 1 );
		namespace Clever_Canyon\PHP_Scoper\Config_File;
		ooo;

		$body = ''; // Initialize.

		$body .= <<<'ooo'
		/**
		 * CLI check.
		 *
		 * @since 2021-12-15
		 */
		if ( 'cli' !== PHP_SAPI ) {
			exit( 1 ); // CLI mode only.
		}
		ooo;
		$body .= "\n\n";

		$body .= <<<'ooo'
		/**
		 * Configuration.
		 *
		 * @since 2021-12-15
		 *
		 * @see https://o5p.me/DsVI6o
		 */
		ooo;
		$body .= "\n";

		$body .= '$cfg = ' .
			var_export( [
				'expose-global-constants' => false,
				'expose-global-classes'   => false,
				'expose-global-functions' => false,

				'exclude-files'     => $exclude_files,
				'exclude-constants' => $exclude_names->constants,
				'exclude-classes'   => $exclude_names->classes,
				'exclude-functions' => $exclude_names->functions,
			], true ) . ';' . "\n";
		$body .= '$cfg[ \'patchers\' ] = [ ' . $patchers . ' ];' . "\n";

		$body .= <<<'ooo'
		if ( is_file( __DIR__ . '/composer.json' ) ) {
			$prj_cfg = file_get_contents( __DIR__ . '/composer.json' );
			$prj_cfg = is_array( $prj_cfg = json_decode( $prj_cfg, true ) ) ? $prj_cfg : [];
			$prj_cfg = $prj_cfg['extra']['clevercanyon']['&']['php_scoper']['cfg'] ?? [];
			$cfg     = array_merge( $cfg, $prj_cfg, [
				'exclude-files'     => array_merge( $cfg['exclude-files'], $prj_cfg['exclude-files'] ?? [] ),
				'exclude-constants' => array_merge( $cfg['exclude-constants'], $prj_cfg['exclude-constants'] ?? [] ),
				'exclude-classes'   => array_merge( $cfg['exclude-classes'], $prj_cfg['exclude-classes'] ?? [] ),
				'exclude-functions' => array_merge( $cfg['exclude-functions'], $prj_cfg['exclude-functions'] ?? [] ),
			] );
		}
		if ( is_file( __DIR__ . '/.scoper.prj.cfg.php' ) ) {
			$prj_cfg = require __DIR__ . '/.scoper.prj.cfg.php';
			$cfg     = array_merge( $cfg, $prj_cfg, [
				'exclude-files'     => array_merge( $cfg['exclude-files'], $prj_cfg['exclude-files'] ?? [] ),
				'exclude-constants' => array_merge( $cfg['exclude-constants'], $prj_cfg['exclude-constants'] ?? [] ),
				'exclude-classes'   => array_merge( $cfg['exclude-classes'], $prj_cfg['exclude-classes'] ?? [] ),
				'exclude-functions' => array_merge( $cfg['exclude-functions'], $prj_cfg['exclude-functions'] ?? [] ),
			] );
		}
		return $cfg;
		ooo;

		return $headers . "\n\n" . $body;
	}

	/**
	 * Compiles patchers.
	 *
	 * @since 2022-02-13
	 *
	 * @return string Patchers.
	 */
	protected static function compile_patchers() : string {
		return <<<'ooo'
			function ( string $file, string $prefix, string $content ) : string {
				static $project_dir; // Memoize.
				$project_dir ??= str_replace( '\\', '/', __DIR__ );

				if ( false === mb_strpos( $file, 'symfony' ) ) {
					return $content; // Not applicable.
				}
				$file         = str_replace( '\\', '/', realpath( $file ) );
				$file_subpath = mb_substr( $file, mb_strlen( $project_dir . '/._x/comp/' ) );

				switch( true ) {
					case (bool) preg_match( '`^vendor/symfony/polyfill-php[^/]+/bootstrap\.php$`u', $file_subpath ):
						var_dump( $file_subpath );
						return $content;
				}
				return $content;
			},
		ooo;
	}

	/**
	 * Compiles files to exclude.
	 *
	 * @since 2022-02-13
	 *
	 * @return array Files to exclude.
	 */
	protected function compile_exclude_files() : array {
		$exclude_files = []; // Initialize.

		foreach ( glob( $this->project->dir . '/src/functions/polyfills/*.php' ) as $_php_file ) {
			$exclude_files[] = '._x/comp/' . U\Dir::subpath( $this->project->dir, $_php_file );
		}
		foreach ( glob( $this->project->dir . '/vendor/symfony/polyfill-php*/bootstrap.php' ) as $_php_file ) {
			$exclude_files[] = '._x/comp/' . U\Dir::subpath( $this->project->dir, $_php_file );
		}
		return $exclude_files;
	}

	/**
	 * Compiles names to exclude.
	 *
	 * @since 2022-01-02
	 *
	 * @return object Object w/ properties containing names of class, functions, etc.
	 *                {@see Config_File::php_parser_node_visitor()} for further details.
	 *
	 * @throws U\Fatal_Exception On any error.
	 */
	protected function compile_exclude_names() : object {
		try {
			$visitor   = $this->php_parser_node_visitor();
			$traverser = $this->php_parser_node_traverser( $visitor );

			foreach ( [
				'php_stubs_wordpress_globals',
				'php_stubs_wordpress_stubs',
				'php_stubs_woocommerce_stubs',
				'php_stubs_woocommerce_packages_stubs',
			] as $_stubs
			) {
				$_parser = $this->php_parser();
				U\CLI::log( '[' . __FUNCTION__ . '()]: Parsing: `' . $_stubs . '()`.' );
				$traverser->traverse( $_parser->parse( $this->{$_stubs}() ) );
			}
			return (object) (array) $visitor;

		} catch ( \Throwable $throwable ) {
			throw new U\Fatal_Exception( $throwable->getMessage() );
		}
	}

	/**
	 * PhpParser instance.
	 *
	 * @since 2022-01-02
	 *
	 * @return PhpParser\Parser PhpParser instance.
	 *
	 * @throws \LogicException On invalid args.
	 */
	protected function php_parser() : PhpParser\Parser {
		return ( new PhpParser\ParserFactory() )->create( PhpParser\ParserFactory::PREFER_PHP7 );
	}

	/**
	 * Produces and returns a node traverser for PhpParser.
	 *
	 * @since 2022-01-02
	 *
	 * @param PhpParser\NodeVisitorAbstract $visitor Visitor; {@see Config_File::php_parser_node_visitor()}.
	 *
	 * @return PhpParser\NodeTraverser Node traverser.
	 */
	protected function php_parser_node_traverser( PhpParser\NodeVisitorAbstract $visitor ) : PhpParser\NodeTraverser {
		$traverser = new PhpParser\NodeTraverser();
		$traverser->addVisitor( new PhpParser\NodeVisitor\NameResolver() );
		$traverser->addVisitor( $visitor );

		return $traverser;
	}

	/**
	 * Produces and returns a node visitor for PhpParser.
	 *
	 * @since 2022-01-02
	 *
	 * @return PhpParser\NodeVisitorAbstract Node visitor.
	 */
	protected function php_parser_node_visitor() : PhpParser\NodeVisitorAbstract {
		return new class extends PhpParser\NodeVisitorAbstract {
			/**
			 * Consts array.
			 *
			 * @since 2022-01-02
			 */
			public array $constants = [];

			/**
			 * Classes array.
			 *
			 * @since 2022-01-02
			 */
			public array $classes = [];

			/**
			 * Functions array.
			 *
			 * @since 2022-01-02
			 */
			public array $functions = [];

			/**
			 * Consts array.
			 *
			 * @since 2022-01-02
			 *
			 * @param PhpParser\Node $node Node.
			 */
			public function leaveNode( PhpParser\Node $node ) : void {
				parent::leaveNode( $node );

				if ( $node instanceof PhpParser\Node\Stmt\Const_ ) {
					foreach ( $node->consts as $_const ) {
						$_fqn = $_const->namespacedName->toString();

						$this->constants[] = $_fqn;
						U\CLI::log( '[' . __FUNCTION__ . '()]: Constant: `' . $_fqn . '`.' );
					}
				} elseif ( $node instanceof PhpParser\Node\Expr\FuncCall && $node->name instanceof PhpParser\Node\Name ) {
					if ( 'define' === $node->name->toString() && count( $node->args ) >= 2 ) {
						if ( $node->args[ 0 ]->value instanceof PhpParser\Node\Scalar\String_ ) {
							$_fqn = $node->args[ 0 ]->value->value;

							$this->constants[] = $_fqn;
							U\CLI::log( '[' . __FUNCTION__ . '()]: Constant: `' . $_fqn . '`.' );
						}
					}
				} elseif ( $node instanceof PhpParser\Node\Stmt\Class_ ) {
					$_fqn = $node->namespacedName->toString();

					$this->classes[] = $_fqn;
					U\CLI::log( '[' . __FUNCTION__ . '()]: Class: `' . $_fqn . '`.' );

				} elseif ( $node instanceof PhpParser\Node\Stmt\Interface_ ) {
					$_fqn = $node->namespacedName->toString();

					$this->classes[] = $_fqn;
					U\CLI::log( '[' . __FUNCTION__ . '()]: Interface: `' . $_fqn . '`.' );

				} elseif ( $node instanceof PhpParser\Node\Stmt\Trait_ ) {
					$_fqn = $node->namespacedName->toString();

					$this->classes[] = $_fqn;
					U\CLI::log( '[' . __FUNCTION__ . '()]: Trait: `' . $_fqn . '`.' );

				} elseif ( $node instanceof PhpParser\Node\Stmt\Function_ ) {
					$_fqn = $node->namespacedName->toString();
					$_fqn = 'x_stubfix_readonly' === $_fqn ? 'readonly' : $_fqn;

					$this->functions[] = $_fqn;
					U\CLI::log( '[' . __FUNCTION__ . '()]: Function: `' . $_fqn . '`.' );
				}
			}
		};
	}

	/**
	 * WordPress globals.
	 *
	 * @since 2022-01-02
	 *
	 * @return string WordPress global stubs.
	 */
	protected function php_stubs_wordpress_globals() : string {
		return U\File::read( U\Dir::name( __FILE__, 6, '/vendor/php-stubs/wordpress-globals/wordpress-globals.php' ) );
	}

	/**
	 * WordPress stubs.
	 *
	 * @since         2022-01-02
	 *
	 * @return string WordPress stubs.
	 *
	 * @future-review Patchwork below works around an unexpected `T_READONLY` token.
	 *                Likely due to a bug in PhpParser. Please reassess when support for PHP 8.1 is ready.
	 *                {@see Config_File::php_parser_node_visitor()} also, where `x_stubfix_readonly` conversion occurs.
	 */
	protected function php_stubs_wordpress_stubs() : string {
		$stubs = U\File::read( U\Dir::name( __FILE__, 6, '/vendor/php-stubs/wordpress-stubs/wordpress-stubs.php' ) );
		return str_replace( 'function readonly(', 'function x_stubfix_readonly(', $stubs );
	}

	/**
	 * WooCommerce stubs.
	 *
	 * @since 2022-01-02
	 *
	 * @return string WooCommerce stubs.
	 */
	protected function php_stubs_woocommerce_stubs() : string {
		return U\File::read( U\Dir::name( __FILE__, 6, '/vendor/php-stubs/woocommerce-stubs/woocommerce-stubs.php' ) );
	}

	/**
	 * WooCommerce packages stubs.
	 *
	 * @since 2022-01-02
	 *
	 * @return string WooCommerce packages stubs.
	 */
	protected function php_stubs_woocommerce_packages_stubs() : string {
		return U\File::read( U\Dir::name( __FILE__, 6, '/vendor/php-stubs/woocommerce-stubs/woocommerce-packages-stubs.php' ) );
	}
}
