<?php
/**
 * Clever Canyon™ {@see https://clevercanyon.com}
 *
 *  CCCCC  LL      EEEEEEE VV     VV EEEEEEE RRRRRR      CCCCC    AAA   NN   NN YY   YY  OOOOO  NN   NN ™
 * CC      LL      EE      VV     VV EE      RR   RR    CC       AAAAA  NNN  NN YY   YY OO   OO NNN  NN
 * CC      LL      EEEEE    VV   VV  EEEEE   RRRRRR     CC      AA   AA NN N NN  YYYYY  OO   OO NN N NN
 * CC      LL      EE        VV VV   EE      RR  RR     CC      AAAAAAA NN  NNN   YYY   OO   OO NN  NNN
 *  CCCCC  LLLLLLL EEEEEEE    VVV    EEEEEEE RR   RR     CCCCC  AA   AA NN   NN   YYY    OOOO0  NN   NN
 */
// <editor-fold desc="Strict types, namespace, use statements, and other headers.">

/**
 * Lint configuration.
 *
 * @since 2021-12-15
 *
 * phpcs:disable WordPress.NamingConventions.ValidVariableName.UsedPropertyNotSnakeCase
 */

/**
 * Declarations & namespace.
 *
 * @since 2021-12-25
 */
declare( strict_types = 1 );
namespace Clever_Canyon\Utilities\Dev\CLI_Tools\PHP_Scoper;

/**
 * Utilities.
 *
 * @since 2021-12-15
 */
use Clever_Canyon\{Utilities as U};

/**
 * File-specific.
 *
 * @since 2021-12-15
 */
use PhpParser;

// </editor-fold>

/**
 * PHP Scoper config file generator.
 *
 * @since 2021-12-15
 */
final class Config_File extends U\A6t\CLI_Tool {
	/**
	 * Project.
	 *
	 * @since 2021-12-15
	 */
	protected U\Dev\Project $project;

	/**
	 * Version.
	 *
	 * @since 2021-12-15
	 */
	protected const VERSION = '1.0.0';

	/**
	 * Tool name.
	 *
	 * @since 2021-12-15
	 */
	protected const NAME = 'PHP_Scoper/Config_File';

	/**
	 * Constructor.
	 *
	 * @since 2021-12-15
	 *
	 * @param string|array|null $args_to_parse Optional custom args to parse instead of `$_SERVER['argv']`.
	 *                                         If not given, defaults internally to `$_SERVER['argv']`.
	 */
	public function __construct( /* string|array|null */ $args_to_parse = null ) {
		parent::__construct( $args_to_parse );

		$this->add_commands( [
			'update' => [
				'callback'    => [ $this, 'update' ],
				'synopsis'    => 'Updates `./dev/libraries/dotfiles/dev/.libs/php-scoper/config.php`.',
				'description' => 'Updates `./dev/libraries/dotfiles/dev/.libs/php-scoper/config.php`. See ' . __CLASS__ . '::update()',
				'options'     => [
					'project-dir' => [
						'optional'     => true,
						'arg_required' => true,
						'description'  => 'Project directory path.',
						'validator'    => fn( $value ) => ( $abs_path = $this->v6e_abs_path( $value, 'dir' ) )
							&& is_file( U\Dir::join( $abs_path, '/composer.json' ) ),
						'default'      => $this->locate_nearest_project_dir(),
					],
				],
			],
		] );
		$this->route_request();
	}

	/**
	 * Command: `update`.
	 *
	 * @since 2021-12-15
	 */
	protected function update() : void {
		try {
			U\CLI::heading( '[' . __METHOD__ . '()]: Updating ...' );

			$project_dir   = U\Fs::abs( $this->get_option( 'project-dir' ) );
			$this->project = new U\Dev\Project( $project_dir );

			$this->update_file();

			U\CLI::done( '[' . __METHOD__ . '()]: Update complete ✔.' );
		} catch ( \Throwable $throwable ) {
			U\CLI::error( $throwable->getMessage() );
			U\CLI::log( $throwable->getTraceAsString() );
			U\CLI::exit_status( 1 );
		}
	}

	/**
	 * Updates config file.
	 *
	 * @since 2022-01-02
	 *
	 * @throws U\Fatal_Exception On any error.
	 */
	protected function update_file() : void {
		U\CLI::output( '[' . __FUNCTION__ . '()]: Regenerating config file ...' );

		$cfg_file1         = U\Dir::name( __FILE__, 6, '/dev/libraries/dotfiles/dev/.libs/php-scoper/config.php' );
		$cfg_file2         = U\Dir::name( __FILE__, 6, '/dev/.libs/php-scoper/config.php' );
		$new_file_contents = $this->generate_config_file_contents();

		foreach ( [ $cfg_file1, $cfg_file2 ] as $_cfg_file ) {
			if ( ! is_file( $_cfg_file ) && ! U\File::make( $_cfg_file, [], false, false ) ) {
				throw new U\Fatal_Exception( 'Failed to create PHP Scoper config file: `' . $_cfg_file . '`.' );
			}
			if ( ! U\File::write( $_cfg_file, $new_file_contents, false ) ) {
				throw new U\Fatal_Exception( 'Failed to update PHP Scoper config file: `' . $_cfg_file . '`.' );
			}
			U\CLI::log( '[' . __FUNCTION__ . '()]: Updated: `' . $_cfg_file . '`.' );
		}
	}

	/**
	 * Generates config file contents.
	 *
	 * @since 2022-01-02
	 *
	 * @return string Config file contents.
	 */
	protected function generate_config_file_contents() : string {
		U\Env::raise_memory_limit();

		$patchers      = $this->compile_patchers();
		$exclude_files = $this->compile_exclude_files();
		$exclude_names = $this->compile_exclude_names();

		$headers = <<<'ooo'
		<?php
		/**
		 * PHP Scoper config file.
		 *
		 * PHP Scoper doesn't automatically know about this file.
		 * You must pass `--config ./dev/.libs/php-scoper/config.php`.
		 *
		 * PLEASE DO NOT EDIT THIS FILE!
		 * This file and the contents of it are updated automatically.
		 *
		 * - Instead of editing this file, please configure `composer.json`. See instructions below.
		 * - Instead of editing this file, modify `./config~prj.php`, which is automatically merged in.
		 * - Instead of editing this file, please review source repository {@see https://o5p.me/LevQOD}.
		 *
		 * @see https://github.com/humbug/php-scoper/blob/master/docs/configuration.md
		 *
		 * @since 1.0.0
		 * @noinspection ALL
		 * phpcs:disableFile
		 */

		/* @formatter:ignore
		-----------------------------------------------------------------------------------------------------------------------
		Example `extra.clevercanyon.&.php_scoper` in `../../../composer.json`:
		-----------------------------------------------------------------------------------------------------------------------
		"extra" : {
			"clevercanyon" : {
				"&" : {
					"php_scoper" : {
						"cfg" : {
							"expose-namespaces"  : [ ],
							"expose-constants"   : [ ],
							"expose-classes"     : [ ],
							"expose-functions"   : [ ],

							"exclude-namespaces" : [ ],
							"exclude-constants"  : [ ],
							"exclude-classes"    : [ ],
							"exclude-functions"  : [ ],
							"exclude-files"      : [ ]
						}
					}
				}
			}
		}
		------------------------------------------------------------------------------------------------- @formatter:/ignore */

		/**
		 * Declarations & namespace.
		 *
		 * @since 2021-12-15
		 */
		declare( strict_types = 1 );
		namespace Clever_Canyon\PHP_Scoper\Config_File;
		ooo;

		$body = ''; // Initialize.

		$body .= <<<'ooo'
		/**
		 * CLI check.
		 *
		 * @since 2021-12-15
		 */
		if ( 'cli' !== PHP_SAPI ) {
			exit( 1 ); // CLI mode only.
		}
		ooo;
		$body .= "\n\n";

		$body .= <<<'ooo'
		/**
		 * Configuration.
		 *
		 * @since 2021-12-15
		 *
		 * @see https://o5p.me/DsVI6o
		 */
		ooo;
		$body .= "\n";

		$body .= '$cfg = ' .
			var_export( [
				'expose-global-constants' => false,
				'expose-global-classes'   => false,
				'expose-global-functions' => false,

				'expose-namespaces' => [], // Supports regexp.
				'expose-constants'  => [], // Supports regexp.
				'expose-classes'    => [], // Supports regexp.
				'expose-functions'  => [], // Supports regexp.

				'exclude-namespaces' => $exclude_names->namespaces, // Supports regexp.
				'exclude-constants'  => $exclude_names->constants,  // Supports regexp.
				'exclude-classes'    => $exclude_names->classes,    // Supports regexp.
				'exclude-functions'  => $exclude_names->functions,  // Supports regexp.
				'exclude-files'      => $exclude_files,             // Relative to config file.
			], true ) . ';' . "\n";
		$body .= '$cfg[ \'patchers\' ] = [ ' . $patchers . ' ];' . "\n";

		$body .= <<<'ooo'
		if ( is_file( __DIR__ . '/../../../composer.json' ) ) {
			$prj_cfg = file_get_contents( __DIR__ . '/../../../composer.json' );
			$prj_cfg = is_array( $prj_cfg = json_decode( $prj_cfg, true ) ) ? $prj_cfg : [];
			$prj_cfg = $prj_cfg['extra']['clevercanyon']['&']['php_scoper']['cfg'] ?? [];

			$cfg     = array_merge( $cfg, $prj_cfg, [
				'expose-namespaces'  => array_merge( $cfg['expose-namespaces'], $prj_cfg['expose-namespaces'] ?? [] ),
				'expose-constants'   => array_merge( $cfg['expose-constants'], $prj_cfg['expose-constants'] ?? [] ),
				'expose-classes'     => array_merge( $cfg['expose-classes'], $prj_cfg['expose-classes'] ?? [] ),
				'expose-functions'   => array_merge( $cfg['expose-functions'], $prj_cfg['expose-functions'] ?? [] ),

				'exclude-namespaces' => array_merge( $cfg['exclude-namespaces'], $prj_cfg['exclude-namespaces'] ?? [] ),
				'exclude-constants'  => array_merge( $cfg['exclude-constants'], $prj_cfg['exclude-constants'] ?? [] ),
				'exclude-classes'    => array_merge( $cfg['exclude-classes'], $prj_cfg['exclude-classes'] ?? [] ),
				'exclude-functions'  => array_merge( $cfg['exclude-functions'], $prj_cfg['exclude-functions'] ?? [] ),
				'exclude-files'      => array_merge( $cfg['exclude-files'], $prj_cfg['exclude-files'] ?? [] ),
			] );
		}
		if ( is_file( __DIR__ . '/config~prj.php' ) ) {
			$prj_cfg = require __DIR__ . '/config~prj.php';

			$cfg     = array_merge( $cfg, $prj_cfg, [
				'expose-namespaces'  => array_merge( $cfg['expose-namespaces'], $prj_cfg['expose-namespaces'] ?? [] ),
				'expose-constants'   => array_merge( $cfg['expose-constants'], $prj_cfg['expose-constants'] ?? [] ),
				'expose-classes'     => array_merge( $cfg['expose-classes'], $prj_cfg['expose-classes'] ?? [] ),
				'expose-functions'   => array_merge( $cfg['expose-functions'], $prj_cfg['expose-functions'] ?? [] ),

				'exclude-namespaces' => array_merge( $cfg['exclude-namespaces'], $prj_cfg['exclude-namespaces'] ?? [] ),
				'exclude-constants'  => array_merge( $cfg['exclude-constants'], $prj_cfg['exclude-constants'] ?? [] ),
				'exclude-classes'    => array_merge( $cfg['exclude-classes'], $prj_cfg['exclude-classes'] ?? [] ),
				'exclude-functions'  => array_merge( $cfg['exclude-functions'], $prj_cfg['exclude-functions'] ?? [] ),
				'exclude-files'      => array_merge( $cfg['exclude-files'], $prj_cfg['exclude-files'] ?? [] ),

				'patchers'           => array_merge( $cfg['patchers'], $prj_cfg['patchers'] ?? [] ),
			] );
		}
		return $cfg;
		ooo;

		return $headers . "\n\n" . $body;
	}

	/**
	 * Compiles patchers.
	 *
	 * @since 2022-02-13
	 *
	 * @return string Patchers.
	 */
	protected function compile_patchers() : string {
		return <<<'ooo'
			function ( string $file, string $prefix, string $content ) : string {
				if ( ! preg_match( '/(?:polyfill|deprecation)/u', $file ) ) {
					return $content; // Saves time.
				}
				static $project_dir, $project; // Memoize.
				static $preg_quote_project_dir, $preg_quote_prefix;

				$project_dir ??= str_replace( '\\', '/', realpath( __DIR__ . '/../../..' ) );
				$project     ??= json_decode( file_get_contents( $project_dir . '/composer.json' ) );

				$preg_quote_project_dir ??= preg_quote( $project_dir, '/' );
				$preg_quote_prefix      ??= preg_quote( $prefix, '/' );

				$file         = str_replace( '\\', '/', realpath( $file ) );
				$file_subpath = preg_replace( '/^' . $preg_quote_project_dir . '\/\._x\/comp(?:-tests)?(?:$|\/)/ui', '', $file );

				switch( true ) {
					case ( ( ! empty( $project->name ) && 'clevercanyon/utilities' === $project->name
								&& preg_match( '/^src\/functions\/polyfills\/[^\/]+\.php$/u', $file_subpath ) )
							|| preg_match( '/^vendor\/clevercanyon\/utilities\/src\/functions\/polyfills\/[^\/]+\.php$/u', $file_subpath ) ):

						return preg_replace( '/^\s*namespace\s+' . $preg_quote_prefix . '\s*;\v?/um', '', $content, 1 );

					case ( preg_match( '/^vendor\/symfony\/polyfill-php[^\/]+\/bootstrap\.php$/u', $file_subpath )
					 	|| preg_match( '/^vendor\/symfony\/polyfill-php[^\/]+\/Resources\/stubs\/[^\/]+\.php$/u', $file_subpath )
					 	|| preg_match( '/^vendor\/symfony\/deprecation-contracts\/function\.php$/u', $file_subpath ) ):

						return preg_replace( '/^\s*namespace\s+' . $preg_quote_prefix . '\s*;\v?/um', '', $content, 1 );
				}
				return $content;
			},
		ooo;
	}

	/**
	 * Compiles files to exclude.
	 *
	 * @since 2022-02-13
	 *
	 * @return array Files to exclude.
	 */
	protected function compile_exclude_files() : array {
		return []; // Nothing to exclude at this time.
	}

	/**
	 * Compiles names to exclude.
	 *
	 * @since 2022-01-02
	 *
	 * @return object Object w/ properties containing names of class, functions, etc.
	 *                {@see Config_File::php_parser_node_visitor()} for further details.
	 *
	 * @throws U\Fatal_Exception On any error.
	 */
	protected function compile_exclude_names() : object {
		try {
			$visitor   = $this->php_parser_node_visitor();
			$traverser = $this->php_parser_node_traverser( $visitor );

			foreach ( [
				'php_stubs_wordpress_globals',
				'php_stubs_wordpress_stubs',
				'php_stubs_woocommerce_stubs',
				'php_stubs_woocommerce_packages_stubs',
			] as $_stubs
			) {
				$_parser = $this->php_parser();
				U\CLI::log( '[' . __FUNCTION__ . '()]: Parsing: `' . $_stubs . '()`.' );
				$traverser->traverse( $_parser->parse( $this->{$_stubs}() ) );
			}
			$exclude_names = (object) (array) $visitor;

			sort( $exclude_names->namespaces, SORT_NATURAL );
			sort( $exclude_names->constants, SORT_NATURAL );
			sort( $exclude_names->classes, SORT_NATURAL );
			sort( $exclude_names->functions, SORT_NATURAL );

			return $exclude_names;

		} catch ( \Throwable $throwable ) {
			throw new U\Fatal_Exception( $throwable->getMessage() );
		}
	}

	/**
	 * PhpParser instance.
	 *
	 * @since 2022-01-02
	 *
	 * @return PhpParser\Parser PhpParser instance.
	 *
	 * @throws \LogicException On invalid args.
	 */
	protected function php_parser() : PhpParser\Parser {
		return ( new PhpParser\ParserFactory() )->create( PhpParser\ParserFactory::PREFER_PHP7 );
	}

	/**
	 * Produces and returns a node traverser for PhpParser.
	 *
	 * @since 2022-01-02
	 *
	 * @param PhpParser\NodeVisitorAbstract $visitor Visitor; {@see Config_File::php_parser_node_visitor()}.
	 *
	 * @return PhpParser\NodeTraverser Node traverser.
	 */
	protected function php_parser_node_traverser( PhpParser\NodeVisitorAbstract $visitor ) : PhpParser\NodeTraverser {
		$traverser = new PhpParser\NodeTraverser();
		$traverser->addVisitor( new PhpParser\NodeVisitor\NameResolver() );
		$traverser->addVisitor( $visitor );

		return $traverser;
	}

	/**
	 * Produces and returns a node visitor for PhpParser.
	 *
	 * @since 2022-01-02
	 *
	 * @return PhpParser\NodeVisitorAbstract Node visitor.
	 */
	protected function php_parser_node_visitor() : PhpParser\NodeVisitorAbstract {
		return new class extends PhpParser\NodeVisitorAbstract {
			/**
			 * Namespaces array.
			 *
			 * @since 2022-01-02
			 */
			public array $namespaces = [ 'PHPUnit' ];

			/**
			 * Consts array.
			 *
			 * @since 2022-01-02
			 */
			public array $constants = [];

			/**
			 * Classes array.
			 *
			 * @since 2022-01-02
			 */
			public array $classes = [];

			/**
			 * Functions array.
			 *
			 * @since 2022-01-02
			 */
			public array $functions = [];

			/**
			 * Consts array.
			 *
			 * @since 2022-01-02
			 *
			 * @param PhpParser\Node $node Node.
			 */
			public function leaveNode( PhpParser\Node $node ) : void {
				parent::leaveNode( $node );

				if ( $node instanceof PhpParser\Node\Stmt\Const_ ) {
					foreach ( $node->consts as $_const ) {
						$_fqn = $_const->namespacedName->toString();

						$this->constants[] = $_fqn;
						U\CLI::log( '[' . __FUNCTION__ . '()]: Constant: `' . $_fqn . '`.' );
					}
				} elseif ( $node instanceof PhpParser\Node\Expr\FuncCall && $node->name instanceof PhpParser\Node\Name ) {
					if ( 'define' === $node->name->toString() && count( $node->args ) >= 2 ) {
						if ( $node->args[ 0 ]->value instanceof PhpParser\Node\Scalar\String_ ) {
							$_fqn = $node->args[ 0 ]->value->value;

							$this->constants[] = $_fqn;
							U\CLI::log( '[' . __FUNCTION__ . '()]: Constant: `' . $_fqn . '`.' );
						}
					}
				} elseif ( $node instanceof PhpParser\Node\Stmt\Class_ ) {
					$_fqn = $node->namespacedName->toString();

					$this->classes[] = $_fqn;
					U\CLI::log( '[' . __FUNCTION__ . '()]: Class: `' . $_fqn . '`.' );

				} elseif ( $node instanceof PhpParser\Node\Stmt\Interface_ ) {
					$_fqn = $node->namespacedName->toString();

					$this->classes[] = $_fqn;
					U\CLI::log( '[' . __FUNCTION__ . '()]: Interface: `' . $_fqn . '`.' );

				} elseif ( $node instanceof PhpParser\Node\Stmt\Trait_ ) {
					$_fqn = $node->namespacedName->toString();

					$this->classes[] = $_fqn;
					U\CLI::log( '[' . __FUNCTION__ . '()]: Trait: `' . $_fqn . '`.' );

				} elseif ( $node instanceof PhpParser\Node\Stmt\Function_ ) {
					$_fqn = $node->namespacedName->toString();
					$_fqn = 'x_stubfix_readonly' === $_fqn ? 'readonly' : $_fqn;

					$this->functions[] = $_fqn;
					U\CLI::log( '[' . __FUNCTION__ . '()]: Function: `' . $_fqn . '`.' );
				}
			}
		};
	}

	/**
	 * WordPress globals.
	 *
	 * @since 2022-01-02
	 *
	 * @return string WordPress global stubs.
	 */
	protected function php_stubs_wordpress_globals() : string {
		return U\File::read( U\Dir::name( __FILE__, 6, '/vendor/php-stubs/wordpress-globals/wordpress-globals.php' ) );
	}

	/**
	 * WordPress stubs.
	 *
	 * @since         2022-01-02
	 *
	 * @return string WordPress stubs.
	 *
	 * @future-review Patchwork below works around an unexpected `T_READONLY` token.
	 *                Likely due to a bug in PhpParser. Please reassess when support for PHP 8.1 is ready.
	 *                {@see Config_File::php_parser_node_visitor()} also, where `x_stubfix_readonly` conversion occurs.
	 */
	protected function php_stubs_wordpress_stubs() : string {
		$stubs = U\File::read( U\Dir::name( __FILE__, 6, '/vendor/php-stubs/wordpress-stubs/wordpress-stubs.php' ) );
		return str_replace( 'function readonly(', 'function x_stubfix_readonly(', $stubs );
	}

	/**
	 * WooCommerce stubs.
	 *
	 * @since 2022-01-02
	 *
	 * @return string WooCommerce stubs.
	 */
	protected function php_stubs_woocommerce_stubs() : string {
		return U\File::read( U\Dir::name( __FILE__, 6, '/vendor/php-stubs/woocommerce-stubs/woocommerce-stubs.php' ) );
	}

	/**
	 * WooCommerce packages stubs.
	 *
	 * @since 2022-01-02
	 *
	 * @return string WooCommerce packages stubs.
	 */
	protected function php_stubs_woocommerce_packages_stubs() : string {
		return U\File::read( U\Dir::name( __FILE__, 6, '/vendor/php-stubs/woocommerce-stubs/woocommerce-packages-stubs.php' ) );
	}
}
