#!/usr/bin/env bash
##
# Clever Canyon™ {@see https://clevercanyon.com}
#
#  CCCCC  LL      EEEEEEE VV     VV EEEEEEE RRRRRR      CCCCC    AAA   NN   NN YY   YY  OOOOO  NN   NN ™
# CC      LL      EE      VV     VV EE      RR   RR    CC       AAAAA  NNN  NN YY   YY OO   OO NNN  NN
# CC      LL      EEEEE    VV   VV  EEEEE   RRRRRR     CC      AA   AA NN N NN  YYYYY  OO   OO NN N NN
# CC      LL      EE        VV VV   EE      RR  RR     CC      AAAAAAA NN  NNN   YYY   OO   OO NN  NNN
#  CCCCC  LLLLLLL EEEEEEE    VVV    EEEEEEE RR   RR     CCCCC  AA   AA NN   NN   YYY    OOOO0  NN   NN
##

##
# Sets strict mode options.
#
# {@see https://o5p.me/pnUV7g}.
#
# @since 2022-02-28
##
set -o  nounset;
set -o  errexit;
set -o errtrace;
set -o pipefail;

##
# Traps errors; for easier debugging.
#
# {@see https://o5p.me/8eGn9c}.
#
# @param int ${1} Exit status code.
#
# @since 2022-02-28
##
function stack_trace() {
	local last_command_status_code=$?;
	set +o xtrace; # {@see https://o5p.me/8eGn9c}.
	local exit_status_code="${1:-1}";

	echo '----------------------------------------------------------------------';
	echo 'Error in '"${BASH_SOURCE[1]}"':'"${BASH_LINENO[0]}";
	echo '`'"${BASH_COMMAND}"'` exited with status `'"${last_command_status_code}"'`.';

	if [[ ${#FUNCNAME[@]} -gt 2 ]]; then
		echo 'Stack Trace:';
		for ((_i=1; _i < ${#FUNCNAME[@]}-1; _i++)); do
			echo " ${_i}: ${BASH_SOURCE[${_i}+1]}:${BASH_LINENO[${_i}]} ${FUNCNAME[${_i}]}(...)";
		done;
	fi;
	echo 'Exiting with status `'"${exit_status_code}"'`.';
	exit "${exit_status_code}";
};
trap stack_trace ERR;
