/**
 * Rehype config file.
 *
 * Rehype is not aware of this config file's location.
 *
 * @note PLEASE DO NOT EDIT THIS FILE!
 * @note This entire file will be updated automatically.
 * @note Instead of editing here, please review <https://github.com/clevercanyon/skeleton>.
 *
 * @see https://github.com/rehypejs/rehype/tree/main/packages/rehype-stringify#options
 */

import pluginAnchorsRelExternalNoFollow from './plugins/anchors/rel-external-nofollow.mjs';
import pluginFootnotesFixAnchors from './plugins/footnotes/fix-anchors.mjs';
import pluginFootnotesFixLabelSection from './plugins/footnotes/fix-label-section.mjs';

import pluginStarryNight from '@microflash/rehype-starry-night';
import pluginAutolinkHeadings from 'rehype-autolink-headings';
import pluginSlug from 'rehype-slug';

/**
 * Defines Rehype configuration.
 */
export default async () => {
    /**
     * Composition.
     */
    return {
        settings: {}, // No settings at this time.
        plugins: [
            pluginFootnotesFixAnchors, // Modifies `remark-gfm` footnote anchors to enforce a `~` prefix.
            pluginFootnotesFixLabelSection, // Modifies `#footnote-label` section at bottom, generated by `remark-gfm` plugin.
            [pluginSlug, { prefix: '~' }], // Auto-generates heading IDs using heading text and counters.
            [pluginAutolinkHeadings, { content: { type: 'text', value: '#' } }], // Auto-links all headings.
            pluginAnchorsRelExternalNoFollow, // Modifies external anchors by adding `rel` attribute for improved SEO.
            pluginStarryNight, // Applies syntax highlighting to fenced code blocks.
        ],
    };
};
